### ISSUE TITLE
More options for mpf-to-string conversion

### ISSUE THREAD

**Issue by fredrik-johansson** [mpmath/mpmath#109]
bc.. More options should be available for to_str, and to the user via nstr/nprint:
- It should be possible to choose whether to display the number in
  fixed-point or floating-point format
- Even with the automatic fixed-point/floating-point detection, the
  threshhold should be configurable
- It should be possible to choose an arbitrary base (2-36). Conversion
  should be efficient for base 2 and 16.
- Directed rounding would be useful (at least in base 10). E.g. for
  printing intervals, so that the printed decimal interval is at least as
  wide as the exact binary one.

p. Original issue for "#109":https://github.com/fredrik-johansson/mpmath/issues/109: "http://code.google.com/p/mpmath/issues/detail?id=69":http://code.google.com/p/mpmath/issues/detail?id=69

p. Original author: "https://code.google.com/u/111502149103757882156/":https://code.google.com/u/111502149103757882156/

**Comment by skirpichev** [comment]
closed in favor of #757.  ``base`` option implemented in #711
