### ISSUE TITLE
lu_solve should detect numerically singular matrices

### ISSUE THREAD

**Issue by vks** [mpmath/mpmath#126]
bc.. >>> A = matrix([[5.6, 1.2], [7./15, .1]])

> > > det(A)
> > > mpf('7.3617327511765746e-18')
> > > cond(A)
> > > mpf('5.6037531825289503e+18')
> > > lu_solve(A,[1,2])
> > > matrix(
> > > [['-3.12426446020118e+17'],
> > >  ['1.45799008142722e+18']])
> > > qr_solve(A,[1,2])
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/vinzent/src/mpmath/mpmath/settings.py", line 135, in g
> > >     return f(_args, *_kwargs)
> > >   File "mpmath/linalg.py", line 272, in qr_solve
> > >     H, p, x, r = householder(extend(A, b))
> > >   File "mpmath/linalg.py", line 202, in householder
> > >     raise ValueError('matrix is numerically singular')
> > > ValueError: matrix is numerically singular

p. Original issue for "#126":https://github.com/fredrik-johansson/mpmath/issues/126: "http://code.google.com/p/mpmath/issues/detail?id=86":http://code.google.com/p/mpmath/issues/detail?id=86

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

p. Original owner: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by skirpichev** [comment]
I seems, this is fixed:
```pycon
>>> lu_solve(zeros(2),[0,0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/matrices/linalg.py", line 225, in lu_solve
    A, p = ctx.LU_decomp(A)
           ^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/matrices/linalg.py", line 132, in LU_decomp
    raise ZeroDivisionError('matrix is numerically singular')
ZeroDivisionError: matrix is numerically singular
>>> A = matrix([[5.6, 1.2], [7./15, .1]])
>>> qr_solve(A,[1,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/matrices/linalg.py", line 408, in qr_solve
    H, p, x, r = ctx.householder(ctx.extend(A, b))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/matrices/linalg.py", line 342, in householder
    raise ValueError('matrix is numerically singular')
ValueError: matrix is numerically singular
```
