### ISSUE TITLE
identify function

### ISSUE THREAD

**Issue by pernici** [mpmath/mpmath#140]
bc.. In revision 758 >>> a = identify(0.521, ['pi', 'e'], tol=1e-4, full=True)

> > > a[0]
> > > 'pi*((12-sqrt(0))/72)'

p. Original issue for "#140":https://github.com/fredrik-johansson/mpmath/issues/140: "http://code.google.com/p/mpmath/issues/detail?id=100":http://code.google.com/p/mpmath/issues/detail?id=100

p. Original author: "https://code.google.com/u/107755593449647463741/":https://code.google.com/u/107755593449647463741/

p. Original owner: "https://code.google.com/u/107755593449647463741/":https://code.google.com/u/107755593449647463741/

**Comment by skirpichev** [comment]
closed as duplicate of #236
