### ISSUE TITLE
support for 2.6 Fraction class

### ISSUE THREAD

**Issue by jbaayen** [mpmath/mpmath#180]
bc.. Quick conversion from Python 2.6 Fractions to mpf/mpi types would be handy.
I currently use the following helper functions:

def mpi_from_frac(a, b=None):
        a = mpf_from_frac(a)
        if b is None:
                b = a
        else:
                b = mpf_from_frac(b)

```
    return mpi(a, b)
```

def mpf_from_frac(a):
        return fraction(a.numerator, a.denominator)

p. Original issue for "#180":https://github.com/fredrik-johansson/mpmath/issues/180: "http://code.google.com/p/mpmath/issues/detail?id=140":http://code.google.com/p/mpmath/issues/detail?id=140

p. Original author: "https://code.google.com/u/104490253617518974981/":https://code.google.com/u/104490253617518974981/

**Comment by skirpichev** [comment]
Everything is working for mpmathify/mpf.  For mpi - NotImplementedError's are raised and everything is clear.  So, lets not keep this open.
