### ISSUE TITLE
Pretty option

### ISSUE THREAD

**Issue by fredrik-johansson** [mpmath/mpmath#193]
```
How about an option mp.pretty = True to make repr = str? This would lead to
slightly cleaner interactive examples.
```

Original issue for #193: http://code.google.com/p/mpmath/issues/detail?id=153
Original author: https://code.google.com/u/111502149103757882156/
Original owner: https://code.google.com/u/111502149103757882156/

**Comment by skirpichev** [comment]
I think this is fixed.
