### ISSUE TITLE
mpmath docstring edits

### ISSUE THREAD

**Issue by smichr** [mpmath/mpmath#209]
```
Version 0.13

As part of sympy editing, I have some docstring edits for mpmath available
from smichr's 1509mpmath branch at github.
```

Original issue for #209: http://code.google.com/p/mpmath/issues/detail?id=169
Original author: https://code.google.com/u/117933771799683895267/

**Comment by skirpichev** [comment]
@smichr, I don't see 1509mpmath in your sympy's repo.  Probably, this issue is fixed now.  Please reopen, if you disagree.
