### ISSUE TITLE
use numpy for fp matrix arithmetic

### ISSUE THREAD

**Issue by vks** [mpmath/mpmath#217]
```
Were in the code should this be implemented? ctx_fp.py? The probably some code has to be 
moved.
```

Original issue for #217: http://code.google.com/p/mpmath/issues/detail?id=177
Original author: https://code.google.com/u/Vinzent.Steinberg@gmail.com/
Original owner: https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by skirpichev** [comment]
Lets close this in favor of #753
