### ISSUE TITLE
mpmath objects and mpi (can't pickle matrices)

### ISSUE THREAD

**Issue by francismotta** [mpmath/mpmath#380]
It appears that mpmath objects do not play well with mpi.  Consider the following minimal (not) working example (I am running python v3.6.0 with mpmath v1.0.0 and mpi4py v2.0.0):

**test.py**

---
from mpi4py import MPI
from mpmath import mp

comm = MPI.COMM_WORLD
num_proc = comm.Get_size()
rank = comm.Get_rank()

if rank == 0:
    comm.send(mp.matrix([[1,2],[3,4]]), dest = 1)

if rank == 1:
    data = comm.recv(source = 0)

---

The command    _mpiexec -n 2 python test.py_    returns the following error: 

_pickle.PicklingError: Can't pickle <class 'mpmath.matrices.matrices.matrix'>: attribute lookup matrix on mpmath.matrices.matrices failed

It appears to be a known issue but without any response regarding a fix.  Is there a known work around?  Thank you.

**Comment by aelzenaar** [comment]
This problem is still around, it appears for me when trying to pass mp.matrix objects around when using the Python multiprocessing library.

**Comment by skirpichev** [comment]
#264 for pickling intervals
