### ISSUE TITLE
Does mpmath has any conflits with pyspark?

### ISSUE THREAD

**Issue by blokhinnv** [mpmath/mpmath#392]
Say, I want to replace all elements in RDD by 5!, here's the code:
```
from math import factorial
from mpmath import fac
def z(row):
#     k = fac(5)
    k = factorial(5)
    return k
RDD = sc.textFile(r"F:\Jupyter\123.csv")\
        .map(lambda line: line.split(","))\
        .map(lambda row: z(row))\
        .take(10)
print(RDD)
```
The problem is if i uncomment the line `k = fac(5)` I get the following error:

> Py4JJavaError                             Traceback (most recent call last)
> <ipython-input-27-a5dead147ac2> in <module>()
>       5     k = factorial(5)
>       6     return k
> ----> 7 RDD = sc.textFile(r"F:\Jupyter\123.csv")        .map(lambda line: line.split(","))        .map(lambda row: z(row))        .take(10)
>       8 print(RDD)
> 
> C:\Spark\spark-2.3.0-bin-hadoop2.7\python\pyspark\rdd.py in take(self, num)
>    1356 
>    1357             p = range(partsScanned, min(partsScanned + numPartsToTry, totalParts))
> -> 1358             res = self.context.runJob(self, takeUpToNumLeft, p)
>    1359 
>    1360             items += res
> 
> C:\Spark\spark-2.3.0-bin-hadoop2.7\python\pyspark\context.py in runJob(self, rdd, partitionFunc, partitions, allowLocal)
>     999         # SparkContext#runJob.
>    1000         mappedRDD = rdd.mapPartitions(partitionFunc)
> -> 1001         port = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
>    1002         return list(_load_from_socket(port, mappedRDD._jrdd_deserializer))
>    1003 
> 
> C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\py4j-0.10.6-src.zip\py4j\java_gateway.py in __call__(self, *args)
>    1158         answer = self.gateway_client.send_command(command)
>    1159         return_value = get_return_value(
> -> 1160             answer, self.gateway_client, self.target_id, self.name)
>    1161 
>    1162         for temp_arg in temp_args:
> 
> C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\py4j-0.10.6-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
>     318                 raise Py4JJavaError(
>     319                     "An error occurred while calling {0}{1}{2}.\n".
> --> 320                     format(target_id, ".", name), value)
>     321             else:
>     322                 raise Py4JError(
> 
> Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
> : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 12.0 failed 1 times, most recent failure: Lost task 0.0 in stage 12.0 (TID 12, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 216, in main
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 58, in read_command
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 170, in _read_with_length
>     return self.loads(obj)
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 559, in loads
>     return pickle.loads(obj, encoding=encoding)
> TypeError: __new__() missing 1 required positional argument: 'p'
> 
> 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:298)
> 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:438)
> 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:421)
> 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:252)
> 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
> 	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
> 	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
> 	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
> 	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
> 	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
> 	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
> 	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
> 	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
> 	at org.apache.spark.api.python.PythonRDD$$anonfun$1.apply(PythonRDD.scala:141)
> 	at org.apache.spark.api.python.PythonRDD$$anonfun$1.apply(PythonRDD.scala:141)
> 	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2067)
> 	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2067)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:109)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Driver stacktrace:
> 	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1587)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1586)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1586)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
> 	at scala.Option.foreach(Option.scala:257)
> 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1820)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
> 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
> 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2048)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2067)
> 	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:141)
> 	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:214)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 216, in main
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\worker.py", line 58, in read_command
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 170, in _read_with_length
>     return self.loads(obj)
>   File "C:\Spark\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\serializers.py", line 559, in loads
>     return pickle.loads(obj, encoding=encoding)
> TypeError: __new__() missing 1 required positional argument: 'p'
> 
> 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:298)
> 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:438)
> 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:421)
> 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:252)
> 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
> 	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
> 	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
> 	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
> 	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
> 	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
> 	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
> 	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
> 	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
> 	at org.apache.spark.api.python.PythonRDD$$anonfun$1.apply(PythonRDD.scala:141)
> 	at org.apache.spark.api.python.PythonRDD$$anonfun$1.apply(PythonRDD.scala:141)
> 	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2067)
> 	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2067)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:109)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	... 1 more

even though I return not mpmath.fac(5) but math.factorial(5). Could you help please, why is this happening?

**Comment by skirpichev** [comment]
@blokhinnv, it's not clear which version you have run.  Could you try it on the recent mpmath, i.e. 1.3.0?

It seems, there was some issue with pickling, but the message looks cryptic for me.  This may be connected with the private mpq class:
```python
>>> import pickle
>>> from mpmath.rational import mpq
>>> a = mpq(1, 2)
>>> pickle.loads(pickle.dumps(a))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() missing 1 required positional argument: 'p'
```
The #691 drops this class.  Could you try you code on this branch as well?

**Comment by blokhinnv** [comment]
First of all, thank you for your reply. This reminded me how I was writing the thesis for my bachelors degree 5 years ago 🥹

The issue is no longer revelant. My bad, I forgot to close it. 

Have a nice day!
