### ISSUE TITLE
Interoperability with MATLAB

### ISSUE THREAD

**Issue by david10e10** [mpmath/mpmath#415]
Has anybody tried to import an interval matrix from INTLAB into mpmath iv matrices? I can use Python and MATLAB for floats using the MATLAB python engine but I'm just wondering if this would be possible for the Interval data type.

**Comment by skirpichev** [comment]
@david10e10, MATLAB and INTLAB are proprietary software.  If you are using that, why just not try to interact with the mpmath?

The iv context has very limited implementation, almost nothing beyond the basic arithmetic is guaranteed to work correctly.  I doubt it can interoperate with the INTLAB.  This is how implemented conversion from other types to iv.mpf:
https://github.com/mpmath/mpmath/blob/08cbde4bfbb2a6079644021fc51b3d179cce1a5e/mpmath/ctx_iv.py#L405-L436

It shouldn't be hard to workaround this, however.  You can transform end-points to rational numbers or to mantissa/exp pairs.  This will allow you to reconstruct mp.mpf and then iv.mpf...

Feel free to reopen this issue, if you think the answer is not clear or you think that mpmath can implement something to better interact with matlab/intlab.
