### ISSUE TITLE
Stale Issues

### ISSUE THREAD

**Issue by warnerjon12** [mpmath/mpmath#424]
It seems that there are a number of issues which are either not applicable or have been resolved but are still open. We could use a clean up of the issues so that all open issues are actively being worked on or in need of work. I will try to compile a list of candidate issues to post here. I do not myself have permission to close issues, but I can reference them for review.

**Comment by warnerjon12** [comment]
Take a look at issues #399, #384, #382, #363, #345, #291, #286, #281, #275, and #271. There may be a few I missed and I have not looked at the history before that, but it is a start.

**Comment by fredrik-johansson** [comment]
Thanks, I closed most of them. Note that the hex() PR hasn't been merged.

**Comment by skirpichev** [comment]
I think all relevant issues (except for #345), mentioned above, are closed.
