### ISSUE TITLE
python_trailing function

### ISSUE THREAD

**Issue by ghost** [mpmath/mpmath#435]
#430 I think this can be improved even more. For numbers with a large number of trailing zeros, a binary reduction thing can be coded where we mask 8 bits first and then 16 bits.
If you liked the idea then I can add a pull request for this.

**Comment by fredrik-johansson** [comment]
Yes, it would definitely be faster for larger numbers. There are also these variants:

    def python_trailing2(n):
        if not n:
            return 0
        low_byte = n & 0xff
        if low_byte:
            return small_trailing[low_byte]
        s = bin(n)
        return len(s) - len(s.rstrip('0'))

    def python_trailing3(n):
        if not n:
            return 0
        low_byte = n & 0xff
        if low_byte:
            return small_trailing[low_byte]
        s = "%x" % n
        s2 = s.rstrip('0')
        t = len(s) - len(s2)
        return 4*t + small_trailing[int(s2[-1],16)]

Can you think of even better ways?

At this point I think I'd like to see some benchmarks (for different sizes of numbers and different numbers of trailing zeros).

**Comment by skirpichev** [comment]
Current implementation (660770cd) seems much better.
