### ISSUE TITLE
almosteq on intervals not reflexive ?

### ISSUE THREAD

**Issue by asmodehn** [mpmath/mpmath#445]
Hi,
I am not familiar just yet with mpmath, yet I am surprised by the behavior of `almosteq` on intervals.

Am I holding this the wrong way ? Any obvious reason I am missing for which this relation is not reflexive ? or is this just a bug ?

```
Python 3.7.2 (default, Jan  8 2019, 16:12:09) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpmath
>>> mpmath.__version__
'1.1.0'
>>> i1 = mpmath.iv.mpf((0,1))
>>> mpmath.iv.almosteq(i1, i1)
>>> print(mpmath.iv.almosteq(i1, i1))
None
>>> i2 = mpmath.iv.mpf((1,2))
>>> print(mpmath.iv.almosteq(i2, i2))
None
```

**Comment by asmodehn** [comment]
I m currently playing around with mpmath, and I find more corner cases not handled properly (curently around interval arithmetic)
I might not use it as expected, but I was curious about : 
- what about having more exhaustive tests, using something like https://hypothesis.readthedocs.io/en/latest/ ?
- If I wanted to implement such tests in mpmath, where would I start from ?
Thanks for the help.

**Comment by fredrik-johansson** [comment]
Thanks for the feedback! Interval arithmetic is handled quite poorly in mpmath; almost nothing beyond basic arithmetic is guaranteed to work correctly. In fact, it would probably be better if we somehow took out all the generic mpmath methods from the interval context and added them back one at a time while verifying individually that they work (with test code).

For implementing tests, just have a look at https://github.com/fredrik-johansson/mpmath/blob/master/mpmath/tests/test_interval.py

**Comment by skirpichev** [comment]
> Any obvious reason I am missing for which this relation is not reflexive ?

Well, you can see affected code here:
https://github.com/mpmath/mpmath/blob/b77d54fbb56f7080ad936383b90e01d238654da7/mpmath/ctx_base.py#L194-L213
Then with ``i1`` you will have ``diff==abst==abss==mpi(0,1)`` and ``err==diff/abst==mpi(0, 'inf')``.  We can't decide inequality ``err<=rel_eps(==mpi('1.7763568394002505e-15', '1.7763568394002505e-15')``.  In the second case we will have ``err==mpi(0,1)`` and then - same story.

I think it's not a bug: intervals can't be ordered.  Some comparisons have to return ``None`` (can't decide).  Same is true for the Mathematica:
```
$ wolframscript
Wolfram Language 14.1.0 Engine for Linux x86 (64-bit)
Copyright 1988-2024 Wolfram Research, Inc.

In[1]:= Interval[0, 1]

Out[1]= Interval[{0, 0}, {1, 1}]

In[2]:= Interval[0, 1] < Interval[0, 1]

Out[2]= Interval[{0, 0}, {1, 1}] < Interval[{0, 0}, {1, 1}]

In[3]:= Interval[0, 1] < Interval[1, 2]

Out[3]= Interval[{0, 0}, {1, 1}] < Interval[{1, 1}, {2, 2}]

In[4]:= Interval[0, 1] <= Interval[1, 2]

Out[4]= True

In[5]:= Interval[0, 1] < Interval[2, 3]

Out[5]= True
```

I think this is not a bug.
