### ISSUE TITLE
Wrong gegenbauer(2,-1,x) results

### ISSUE THREAD

**Issue by yixin-09** [mpmath/mpmath#461]
The gegenbauer(2,-1,x) should return 1.0 for any given x
due to its formula, however, in mpmath, it return 0.0 for any given x.

For example:
`mp.dps = 200`
`print gegenbauer(2,-1.0, 27397079.00297188)`

Output is:
`0`

**Comment by skirpichev** [comment]
@yixin-09, I'm not sure which "formula" do you refer above.  In fact (the documentation has a correct mathematical definition for the `gegenbauer()`, but incorrectly calls this "the Gegenbauer polynomial"), the `gegenbauer()` tries to implement the Gegenbauer function:
https://functions.wolfram.com/HypergeometricFunctions/GegenbauerC3General/02/

So, the returned value seems ok for me:
https://functions.wolfram.com/HypergeometricFunctions/GegenbauerC3General/03/01/02/0002/
What do you think?
