### ISSUE TITLE
Incorrect result from gegenbauer function of order 0

### ISSUE THREAD

**Issue by jacksonvanover** [mpmath/mpmath#494]
mpmath version: 1.1.0

Though the gegenbauer polynomial of degree zero is defined to be 1 over its whole domain, we get a result of 0.0 when the second argument is 0. This is true in both the fp and mp contexts.

Example:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> mp.gegenbauer(0, 0, 2.2)
mpf('0.0')
>>> mp.gegenbauer(0, 1, 2.2)
mpf('1.0')
>>> mp.gegenbauer(0, 4, 2.2)
mpf('1.0')
>>> mp.gegenbauer(0, 0, 1.8)
mpf('0.0')
>>> mp.gegenbauer(0, 1, 1.8)
mpf('1.0')
```

**Comment by skirpichev** [comment]
I don't think there are incorrect results.  The mpmath implements same convention as the Mathematica, for example ([GegenbauerC](https://reference.wolfram.com/language/ref/GegenbauerC.html)): i.e. `gegenbauer(n, 0, x)` is zero.

**Comment by jacksonvanover** [comment]
Thanks for addressing this!

I see that in the documentation you listed, it is expected that the polynomial evaluates to 0 whenever the second arg is 0 regardless of the first and third arguments. The source of my confusion is that, according to other resources like https://mathworld.wolfram.com/GegenbauerPolynomial.html, the order 0 gegenbauer polynomial is a constant one (see equation 3 on that page). SciPy and GSL also both adopt this convention. It is unclear to me then what is "correct" in this case, i.e., whether a 0 in the first arg or the second arg should take precedence. Perhaps evaluating order 0 at 0 makes no sense? Perhaps it is sufficient to just leave it up to developer choice and just document the expected behavior?

(Disclaimer that I am no numerical expert, just a curious student working on zero-knowledge tools for correctness in numerical programs)

**Comment by skirpichev** [comment]
Your reference is valid for the Gegenbauer polynomials, while the `gegenbauer()` (according to the formula in its docstring) tries to implement the Gegenbauer function:
https://functions.wolfram.com/HypergeometricFunctions/GegenbauerC3General/02/
(c.f.
https://functions.wolfram.com/Polynomials/GegenbauerC3/)

**Comment by jacksonvanover** [comment]
I see; I am unfamiliar with the difference. I will have to do some reading. Thanks!
