### ISSUE TITLE
mpmath failed test 

### ISSUE THREAD

**Issue by ali-parvizi** [mpmath/mpmath#515]
this test failed, what should I do?

anaconda3/lib/python3.7/site-packages/mpmath/tests/test_quad.py ...............x                          [ 93%]

**Comment by MaxGaukler** [comment]
xfail means "expected to fail", this is used for writing tests against bugs that are not fixed yet.
`pytest --runxfail` gives more information on which test failed expectedly.

**Comment by skirpichev** [comment]
@ali-parvizi, obviously you can try to fix failed test.
