### ISSUE TITLE
mpf arithmetics with inf or nan are inconsistent with python float

### ISSUE THREAD

**Issue by sylee957** [mpmath/mpmath#516]
```
>>> float(1) ** float('inf')
1.0
>>> mpf(1) ** mpf('inf')
mpf('nan')

>>> float('nan') ** float(0)
1.0
>>> mpf('nan') ** mpf(0)
mpf('nan')
```
These questions have arised from 
https://github.com/sympy/sympy/issues/18500
https://github.com/sympy/sympy/issues/18470
But the inconsistency of mpmath and python arithmetic itself is making the thoughts complicated.
Is it intended or is it a bug of mpmath?

**Comment by skirpichev** [comment]
FYI, decimal module:
```
>>> from decimal import Decimal
>>> Decimal('NaN')**0
Decimal('NaN')
>>> 1**Decimal('Infinity')
Decimal('1.000000000000000000000000000')
```
