### ISSUE TITLE
Unexpected return from mp.hermite when evaluating limit

### ISSUE THREAD

**Issue by jacksonvanover** [mpmath/mpmath#523]
When evaluating the limit approaching infinity of the hermite polynomial of degree zero, SciPy, GSL, and even the fp version of mpmath function agree that the output should be 1. However, `mp.hermite(0, inf)` evaluates to NaN.

```
>>> fp.hermite(0, np.inf)
1.0
>>> special.eval_hermite(0, np.inf) 
1.0
>>> mp.hermite(0, np.inf)
mpf('nan')
```

**Comment by skirpichev** [comment]
That seems due to:
```pycon
>>> fp.power(inf, 0.0)
1.0
>>> mp.power(inf, 0.0)
mpf('nan')
```
