### ISSUE TITLE
Deprecation warning from six.py

### ISSUE THREAD

**Issue by rikardn** [mpmath/mpmath#524]
I get the following warning from mpmath (when using it via sympy):

```
.tox/py37/lib/python3.7/site-packages/mpmath/libmp/six.py:74
  /home/user/devel/myproj/.tox/py37/lib/python3.7/site-packages/mpmath/libmp/six.py:74: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    __import__(name)
```

I'm using mpmath 1.1.0 from PyPI.

**Comment by rikardn** [comment]
It turns out that it was actually this warning that was triggered:

``` 
  .tox/py38/lib/python3.8/site-packages/mpmath/libmp/six.py:74: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    __import__(name)
```

And it was due to ```pyfakefs``` doing patching of mpmath. Adding mpmath to ```Patcher.SKIPNAMES``` stopped trigging the warnings.

I'll leave the issue open since it feels like mpmath is doing something non-standard here.

**Comment by skirpichev** [comment]
No py2 support anymore after #629

**Comment by rikardn** [comment]
Thanks for the fix and the update!
