### ISSUE TITLE
Metaclassing causes different classes for custom contexts

### ISSUE THREAD

**Issue by sylee957** [mpmath/mpmath#532]
```python3
import mpmath
from mpmath import MPContext

mp = mpmath.mp
mp0 = MPContext()

print(isinstance(mp.matrix([[1, 2], [3, 4]]), mp.matrix))
print(isinstance(mp.matrix([[1, 2], [3, 4]]), mp0.matrix))
print(isinstance(mp0.matrix([[1, 2], [3, 4]]), mp.matrix))
print(isinstance(mp0.matrix([[1, 2], [3, 4]]), mp0.matrix))

print(isinstance(mp.mpf(1), mp.mpf))
print(isinstance(mp.mpf(1), mp0.mpf))
print(isinstance(mp0.mpf(1), mp.mpf))
print(isinstance(mp0.mpf(1), mp0.mpf))

print(isinstance(mp.mpq(1), mp.mpq))
print(isinstance(mp.mpq(1), mp0.mpq))
print(isinstance(mp0.mpq(1), mp.mpq))
print(isinstance(mp0.mpq(1), mp0.mpq))
```

I see mp contexts are creating different classes on fly, but only `mpq` is hardcoded to a single class.
How should I check if a class is generally an instance of mpf or matrix across every contexts? Were those metaclsses necessary for mpf and matrix?

**Comment by oscarbenjamin** [comment]
> you could check as `isinstance(obj, ctx.class)` (where `class` e.g. `mpf`).

This only works if you know which context the mpf should be from. The question is how to test if an object is an mpf presumably in a situation like an `__add__` method where you need to check what kind of object you have:
```python
def __add__(self, other):
    if isinstance(other, ...):
        return ...
```
All mpfs are subclasses of the internal `_mpf` class but that appears not be public.

I think it would be better not to use dynamically created `mpf` classes for each context (gh-696).

**Comment by skirpichev** [comment]
> This only works if you know which context the mpf should be from.

Or you could *find* those context from some candidates.

> All mpfs are subclasses of the internal _mpf class but that appears not be public.

All numeric types (but not mpq) of the mpmath have the context attribute...  So, in your setup the only option is, probably, use duck typing, e.g.: `if hasattr(obj, 'context') and isinstance(obj, obj.context.mpf): ...`

> I think it would be better not to use dynamically created mpf classes for each context

Yes, I think so.

Let me know if you do think I should reopen this issue.

**Comment by oscarbenjamin** [comment]
> Let me know if you do think I should reopen this issue.

I think that gh-696 is fine for this.
