### ISSUE TITLE
Issue in Converting scientific notation to equivalent decimal 

### ISSUE THREAD

**Issue by shubhamkumarpanday** [mpmath/mpmath#546]
http://mpmath.org/doc/1.1.0/general.html#conversion-and-printing

Hello mpmath team, 
mpmath library is awesome. I am using mpmath library in my  project. got stuck while converting 
x = '2.74650025508198e+107310'
y = mpmath.mpmathify(x)
here I am unable to convert scientifc notatioin to  actual number. (It is generating nearest number)
can you please help me out how to resolve the issue.

here is my sample test code.
```python
from mpmath import *
import random

def test(num):
  print(num)
  num_mpf = mpmathify(num)
  num_nstr = nstr(num_mpf, len(str(num)))
  #removing .0 from num_nstr
  without_zero = num_nstr[slice(len(num_nstr)-2)]
  print(without_zero)
  if str(num) == without_zero:
    #print('In this scenario bigint is converting into scientific notation')
    # print('its working fine, when i am passing the num_mpf object to nstr')
    print(True)
  else:
    print(False)

  print('---------------------')
  #case two 
  num_nstr_two =  nstr(mpmathify(str(num_mpf)), len(str(num)))
  print(str(num_mpf))
  print(num_nstr_two)
  without_zero_two = num_nstr_two[slice(len(num_nstr_two)-2)]
  print(without_zero_two)
  if str(num) == without_zero_two:
    print(True)
  else:
    print('Failing in this scenario when Iam converting scientifc string to its equivalent decimal')
    print(False)

def check(x):
  for i in range(x):
    y = random.randint(9**19, 10**19)
    test(y)
    print('$$$$$$$$$$$$$$$$')

check(1)
```
how to overcome this problem?

Recently I did testing for scientific notation to equivalent decimal. I found that It's working till this 999999999999999 correctly
after that it's not converting correctly string scientific notation number to equivalent decimal

mpmath.nstr(mpf('2.74650025508198e+107310'), 107311) isn't converting to correct number.

**Comment by wanfuse123** [comment]
"Processed base X, power Y"
"Base: X, Power: Y"
"Value: len(1.0e+Z)"
"value_str: 1.0e+Z"

Where X, Y, and Z are very large numbers
same issue I think 
working in python
have set a few limits
things tried
setting limits up to rediculous values
    mp.prec = 1986700
    mp.dps = 1986700
    mpmath.mp.dps = 1986700
    # Set the desired precision
    mpmath.mp.dps = precision
    
emacs -q --no-site-file base_power_lengths.csv
export PYTHONINTMAXSTRDIGITS=0  << cython limit see email

**Comment by skirpichev** [comment]
> mpmath.nstr(mpf('2.74650025508198e+107310'), 107311) isn't converting to correct number.

@shubhamkumarpanday, could you say which "correct number" do you expect here?

**Comment by skirpichev** [comment]
Ok, I would guess that you should increase prec/dps to get a "correct number".  Consider this example:
```pycon
>>> nstr(mpf('2.746501e+10'), 10)
'2.746501e+10'
>>> nstr(mpf('2.746501e+10'), 11)
'27465010000.0'
>>> mp.dps = 5  # now try with lower dps
>>> nstr(mpf('2.746501e+10'), 11)
'27465023488.0'
```

I don't think there is something wrong with mpmath.  But feel free to reopen the issue, if you think there is a bug.  Please provide more info, however (what you did, what was expected, what you got instead, etc).
