### ISSUE TITLE
Maintainership of mpmath

### ISSUE THREAD

**Issue by skirpichev** [mpmath/mpmath#550]
In some sense, this is a recreation of https://github.com/fredrik-johansson/mpmath/issues/399 (which was closed).  But, probably, this is - the right place to discuss the project maintainership, instead of the sympy's maillists (where I can't reply, while your project is an important dependency for me).

@fredrik-johansson , while I strongly appreciate [your efforts](https://groups.google.com/g/sympy/c/dRzAOoi1B0Q) to find new maintainers in the sympy community - moving your project to the sympy github group umbrella will mean, that you block me from the mpmath development entirely.  Perhaps, I will be not alone.  Do I did something wrong or disrespectful for you or your projects?  (BTW, perhaps from the Diofant & me - you got not too less merged pull requests then from SymPy devs ;))

I hope, this issue may be solved without sharing the toxic CoC (Contributor Covenant) policy, which was
adopted by the sympy folks.  For example, you can create a separate organization just for this project (e.g. mpmath),
transfer the project and invite some contributors (e.g. those who will come from your sympy maillist thead); you call
this - a second choice.  (I think, you can even add an entirely some group of developers, e.g. sympy.)  But _you_ - will be the community leader and _you_ - will decide on the project policy matters.  I believe - this will be an easy task; I don't remember that you block anyone on wipe out issues and/or comments.

PS: Maybe it's even worthless to transfer the project - just invite someone to help with this repo.

**Comment by fredrik-johansson** [comment]
Hi Sergey,

If I find enough people willing to volunteer to run mpmath independent of SymPy, I'm fine with that too. Nevertheless, SymPy is the project with the most stakes in mpmath, and I think there could be a lot to gain -- improvements to SymPy requiring simultaneous mpmath patches (and frequent releases), website administration, GSoC projects, and so on.

I appreciate your contributions to mpmath and it would be unfortunate if you were not able to contribute anymore. I will certainly consider that. If mpmath moves to the SymPy umbrella, I can at least make the request to allow you to participate in mpmath development.

By the way, the mail was also posted to the mpmath mailing list.

**Comment by skirpichev** [comment]
> SymPy is the project with the most stakes in mpmath, and I think there could be a lot to gain -- improvements to SymPy requiring simultaneous mpmath patches (and frequent releases), website administration, GSoC projects, and so on.

I don't sure if such improvements have constraint that you transfer project ownership to the sympy team.  All this - just require contributors (and here now nothing prevents to contribute for sympy people) and maintainers.  But you will not gain them automatically if mpmath moves to the SymPy umbrella (apparently, not everyone from the sympy team will participate in code reviews even if you allow this for all sympy group - then why don't add only people who would be interested?).

**Comment by WarrenWeckesser** [comment]
It has been over a year since https://groups.google.com/g/mpmath/c/v8VjGgR1HH4.  Aaron Meuer seemed to support moving mpmath to the SymPy github org.  I think it is time to just do it.

The [SymPy CoC](https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md) looks pretty bland to me (TL;DR: be polite).

**Comment by skirpichev** [comment]
> Aaron Meuer seemed to support moving mpmath to the SymPy github org. I think it is time to just do it.

During this year nobody from the SymPy org volunteered to do pull requests review or fix some bugs.  Why do you think this change does make sense?

**Comment by WarrenWeckesser** [comment]
Mainly based on @asmeurer's comments in the email of 10-Sep-2020.  The current status doesn't seem to be working, so it seems worthwhile to try that proposal.

**Comment by skirpichev** [comment]
On Sat, Nov 06, 2021 at 11:14:20PM -0700, Warren Weckesser wrote:
>    Mainly based on ***@***.***'s comments in the email of 10-Sep-2020. The
>    current status doesn't seem to be working, so it seems worthwhile to try
>    that proposal.

Nothing forbid SymPy people to help right now.

**Comment by WarrenWeckesser** [comment]
That's true, as far as I can see, so I don't know if the move to the SymPy org would improve things.  But there is also the fact that @fredrik-johansson made the suggestion to move to SymPy as his first preference, and @asmeurer was in favor of it.  Perhaps the move could be contingent on getting a commitment from an appropriate set of developers to become mpmath maintainers (and from the little that I've looked at the mpmath history, you should be part of that).

**Comment by oscarbenjamin** [comment]
The potential advantage of moving mpmath so SymPy would be that we could manage basic maintenance like putting out releases and updating to new Python versions. What I don't know is if anyone within the SymPy project (or from anywhere else) has a good enough understanding of mpmath itself to be able to do more significant maintenance like deciding on new features, making a roadmap etc.

**Comment by fredrik-johansson** [comment]
I am quite interested in features and roadmaps, but I really don't have time for the basic maintenance (as you can see).

**Comment by oscarbenjamin** [comment]
Well then I think it can work. My proposal would be:

1. Move the mpmath repo into the sympy GitHub organisation.
2. Ensure that @skirpichev can continue to contribute to the repo.
3. SymPy folks can manage basic maintenance like updates and releases.
4. @fredrik-johansson can still be responsible for the overall direction of mpmath.

Does that seem reasonable?

Apart from the (not very active) mpmath mailing list are there any other forums that could be used to reach people who might need to know about this or who might have alternative suggestions?

CC @asmeurer @certik

**Comment by cbm755** [comment]
This seems like a reasonable plan to me.  I think having organizations as parents to projects are a good idea: having let one of my projects languish recently, I now think its good to pre-emptively have the main repo somewhere that is shared with others.

**Comment by oscarbenjamin** [comment]
Thanks @cbm755. It also seems reasonable to me (being the idea that I suggested!). I was hoping for more of a response from the other involved parties though...

Do we need a meeting or something to take this forwards or are people happy to agree something here?

**Comment by skirpichev** [comment]
Probably, this could be discussed right here.  But I suspect, that your conditions are inconsistent. SymPy has CoC organization-wide, so if you do (1) - (2) condition out of the question.  Anyway, I still don't understand what forbids SymPy people from contributing right now.  Surely, Fredrik could add someone from the SymPy team as co-maintainer(s?) to do (3).

**Comment by certik** [comment]
> Well then I think it can work. My proposal would be:
> 
>     1. Move the mpmath repo into the sympy GitHub organisation.
> 
>     2. Ensure that @skirpichev can continue to contribute to the repo.
> 
>     3. SymPy folks can manage basic maintenance like updates and releases.
> 
>     4. @fredrik-johansson can still be responsible for the overall direction of mpmath.
> 
> 
> Does that seem reasonable?
> 
> Apart from the (not very active) mpmath mailing list are there any other forums that could be used to reach people who might need to know about this or who might have alternative suggestions?
> 
> CC @asmeurer @certik

This plan is fine with me. Keeping separate is fine with me too.

**Comment by asmeurer** [comment]
This sounds fine to me too. We also need to make sure that someone can make releases on PyPI.

**Comment by skirpichev** [comment]
(Here is my reply to private message from Oscar.  I believe, it's ok to be here, because some announce was planned anyway.)

On Wed, Feb 02, 2022 at 12:25:22AM +0000, Oscar Benjamin wrote:
> I see you've closed a bunch of PRs you had open for mpmath. I presume
> that's because of my message on the sympy mailing list.

No.  I haven't seen your message at all.

The motivation was following.  My oldest pr was about 1yr old.  Apparently, it's not going to be reviewed.  Also, since ~1.5years - no people from the sympy community offer real help to Fredrik.  Unfortunately, my project has (so far) this dependency and I would like to see some bugfixes in.

Hence, I did this fork: https://github.com/diofant/mpmath1/
It's intended to be a backward compatible with the mpmath v1, don't expect new big features: only bugfixes, documentation improvements, new tests and so on.  First release will be till the end of this month.  I would appreciate any help.

> I was intending that you would still be able to contribute to mpmath
> regardless of whether the repo moves under the sympy GH organisation.
> 
> Do you think that that is not possible or is it something that you
> would not be prepared to do?
> 
> In any case I don't want to prevent your contributions so I would like
> to know what would be needed to make that possible.

https://groups.google.com/g/sympy/c/O3krMchaEfg/m/HV0UB1WRAgAJ

That message?

**Comment by skirpichev** [comment]
Let's close this.

In case someone else is willing to help:
https://groups.google.com/g/mpmath/c/08tD8Eqb5ZU
