### ISSUE TITLE
How to run svd_r_raw?

### ISSUE THREAD

**Issue by pygabc1** [mpmath/mpmath#556]
I like to run svd_r_raw, and how to run it? 
Also, in svd_r_raw(ctx, ...) what is ctx?
How to call ctx?
Thanks.

**Comment by thartmann15** [comment]
svd_r_raw is not meant to be called directly. use svd_r instead:
       >>> from mpmath import mp
       >>> A = mp.matrix([[2, -2, -1], [3, 4, -2], [-2, -2, 0]])
       >>> S = mp.svd_r(A, compute_uv = False)
If you really, really want to use svd_r_raw directly (ctx has to be mp):
      >>> from mpmath.matrices.eigen_symmetric import svd_r_raw;
      >>> svd_r_raw(mp,A)
