### ISSUE TITLE
Minor error in lambertw at -1/e for branches 0 and -1

### ISSUE THREAD

**Issue by paulmasson** [mpmath/mpmath#563]
With version 1.1.0:
```
>>> lambertw(-exp(-1),0)
mpc(real='-1.0', imag='8.2200797148366183e-9')
>>> lambertw(-exp(-1),-1)
mpc(real='-1.0', imag='-8.2200797148366183e-9')
```
These should be exactly -1. Perhaps best handled as a special case.

**Comment by fredrik-johansson** [comment]
-exp(-1) is not exact, so this is not a surprise.

**Comment by skirpichev** [comment]
@fredrik-johansson, I'm going to close this.  I don't see similar special cases across the codebase.
