### ISSUE TITLE
Publish v1.2.0 release on PyPI

### ISSUE THREAD

**Issue by skirpichev** [mpmath/mpmath#565]
Last release is 1.1.0, from 2018.  I think, it's time to provide another one.  It would be great, if the new mpmath will enter to the Debian testing before soft freeze (2021-02-12).

**Comment by sandrotosi** [comment]
@fredrik-johansson i'm echoing what @skirpichev said: Debian just entered the (long) release phase, where new releases are still accepted by they should be released "soon" -- would it be possible for you to cut a new release so that we could package it for debian? thanks!

**Comment by fredrik-johansson** [comment]
OK. Do you have any outstanding issues that need to be fixed before issuing a new release?

**Comment by skirpichev** [comment]
Broken CI looks severe enough for me.

**Comment by fredrik-johansson** [comment]
I merged #554. I can merge an updated #555 if you prefer. My understanding is that GH Actions will be better going forward?

**Comment by skirpichev** [comment]
@fredrik-johansson, I prefer GA over Trarivs, because it's significantly faster on my problems, due to higher number of parallel jobs and so on.  For mpmath it seems also ~2x faster, but I don't think this is a big deal: tests running time < 1/2hour and the project is no so active anymore...

I did update of #555.   setup.cfg changes worth merging anyway.

Please take quick look on other PR's, maybe something could be merged for next release.

**Comment by oscarbenjamin** [comment]
Travis is closing down its free tier so I think mpmath will be forced to move over to something else. Github Actions seems a good choice right now and is what many projects including sympy have moved over to.

**Comment by skirpichev** [comment]
@sandrotosi, I hope you can package the development version of the mpmath in case if no release happens soon.

**Comment by sandrotosi** [comment]
sure i can, but i would prefer not to release a git snapshot for the next stable release of debian (lifetime expected: 5+years)

**Comment by skirpichev** [comment]
@sandrotosi, stable release will be better, of course, but it's out of our control.  At least, I expect that annoying https://bugs.debian.org/953288 should be fixed, regardless of the upstream release status.  Something like 1st Feb is a deadline, if we want this change enter the bullseye (soft freeze at 12-02-21 and there is a 10 days delay).

**Comment by sandrotosi** [comment]
@skirpichev thanks for your concerns, i know how to navigate the debian freeze; there is still plenty of time before we can no longer update mpmath, and @fredrik-johansson said he's gonna prepare a release soon. no need to panic.

**Comment by fredrik-johansson** [comment]
I will do a new release tomorrow, unless something unexpected happens.

**Comment by fredrik-johansson** [comment]
Tagged 1.2.0. If something is wrong, I'll do a 1.2.1.

**Comment by fredrik-johansson** [comment]
Is anyone interested in being added as a maintainer to PyPi for uploading new versions? (I can't be bothered right now.)

**Comment by sandrotosi** [comment]
> Is anyone interested in being added as a maintainer to PyPi for uploading new versions? (I can't be bothered right now.)

maybe this could be a more automatic approach:
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
?

-- 
Sandro "morph" Tosi
My website: http://sandrotosi.me/
Me at Debian: http://wiki.debian.org/SandroTosi
Twitter: https://twitter.com/sandrotosi

**Comment by skirpichev** [comment]
> Is anyone interested in being added as a maintainer to PyPi for uploading new versions? (I can't be bothered right now.)

@fredrik-johansson, I hope, I can help.  But I'm affraid it's already too late for the Debian(

For future, I would suggest automating pypi releases with GA, as @sandrotosi said. If you just add API key on the PyPI - I'll (or someone else) prepare a PR to automate future PyPI uploads.  BTW, it's possible to automate all release stuff, i.e. releases on the Github, documentation upload an so on (see [example](https://github.com/diofant/diofant/blob/master/.github/workflows/test.yml) in the Diofant repo).

**Comment by skirpichev** [comment]
Ok, here it is: https://github.com/fredrik-johansson/mpmath/pull/568

**Comment by sandrotosi** [comment]
> @fredrik-johansson, I hope, I can help. But I'm affraid it's already too late for the Debian(

please do not spread misinformation: it is not too late to include
this new release in the upcoming debian stable release (as a matter of
fact, i'm working on the update *right now*), and precisely the reason
i prodded this issue a few days ago.


-- 
Sandro "morph" Tosi
My website: http://sandrotosi.me/
Me at Debian: http://wiki.debian.org/SandroTosi
Twitter: https://twitter.com/sandrotosi

**Comment by sandrotosi** [comment]
> Tagged 1.2.0. If something is wrong, I'll do a 1.2.1.

Built fine on Debian, so i've just uploaded it to our repo

**Comment by skirpichev** [comment]
Thank you, all.  Probably, I should close this issue.

However, It would be great if 1.2.0 will come on PyPI as well.

**Comment by sandrotosi** [comment]
> However, It would be great if 1.2.0 will come on PyPI as well.

which is probably the reason @fredrik-johansson left it open when he announced 1.2.0?

**Comment by skirpichev** [comment]
Well, issue was about the release for upcoming debian.  Nothing more can be done in this sense.

I'll reopen one, however, per your request.

**Comment by skirpichev** [comment]
Well, probably @fredrik-johansson won't accept my help with pypi uploads.  Maybe someone from the SymPy community can be added as a maintainer to PyPI?  It seems to be trivial, there is no wheels (for now): we need just to upload the [published source package](https://mpmath.org/files/mpmath-1.2.0.tar.gz).  @asmeurer, what do you think?  In future, this can be [automated by CI](https://github.com/fredrik-johansson/mpmath/pull/568).

The release is more than a week old, but there is no new version on the PyPI yet.

**Comment by oscarbenjamin** [comment]
@skirpichev What I would like to do is move mpmath into the sympy repo and then ensure that you still have access to be able to contribute to it. Does that seem reasonable to you @skirpichev @fredrik-johansson ?

**Comment by skirpichev** [comment]
> What I would like to do is move mpmath into the sympy repo and then ensure that you still have access to be able to contribute to it.

@oscarbenjamin, I doubt it's possible.  Other people rule SymPy, not you.  Given this, I'm afraid, it's possible to pick something one from above possibilities.

BTW, this doesn't solve the PyPI upload problem.

**Comment by skirpichev** [comment]
@oscarbenjamin, @asmeurer  almost a year pass since Frederik requested a help.  Let me know if it's my little person stops sympy people from being helpful.  Any maintenance, probably, is better then nothing and I won't mind if I'll loose my ability to contribute in this software.
