### ISSUE TITLE
incorrect power calculation

### ISSUE THREAD

**Issue by metelev-sv** [mpmath/mpmath#587]
Hello!
mpmath.power() fails with negative numbers. Initially I expect to have something like -8**(1./3)=-2. In reality there are 3 roots for 1./3 power and ok, let it be some other answer. But why I didn't get exact 1.0 as a real part and exact sqrt(3) as imaginary part?

$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpmath
>>> mpmath.mp.dps=50
>>> mpmath.power(-8.0,1./3)
mpc(real='1.0000000000000000622086928455818618679774324989807018', imag='1.7320508075688771687514964885913910681346917057935831')
>>> mpmath.sqrt(3)
mpf('1.732050807568877293527446341505872366942805253810381')

**Comment by skirpichev** [comment]
@metelev-sv, it seems, mpmath uses principal value of `exp(y*log(x))` for `power(x, y)`, just like Mathematica does:
```
$ wolframscript 
Wolfram Language 12.2.0 Engine for Linux x86 (64-bit)
Copyright 1988-2021 Wolfram Research, Inc.

In[1]:= Power[-8, 1/3]

              1/3
Out[1]= 2 (-1)

In[2]:= ComplexExpand[%1]

Out[2]= 1 + I Sqrt[3]

In[3]:= %1 // N

Out[3]= 1. + 1.73205 I
```

I doubt there is something incorrect.  Yet, maybe it's a documentation bug.

**Comment by skirpichev** [comment]
BTW, you can get an "expected" answer with
```
>>> mpmath.root(-8, 3, 1)
mpf('-2.0')
```

**Comment by metelev-sv** [comment]
Thank you for answer!

Principal value should have real part exact 1., but it contains some digits after 16 position, though mp.dps=50. And the same for imaginary part, it should be exact sqrt(3) and it is equal for sqrt(3) only for first 15 digits.

By the way, mathematica has similar problem. It gives exact 1. for real part, but not exact Sqrt[3] for imaginary part. I did write to them also.

**Comment by asmeurer** [comment]
The problem is you are using `1./3`, which creates the Python float `0.3333333333333333`. This only approximates 1/3 to 15 digits, the number of digits of a Python machine float. If you want more digits than that, you have to use a function that allows mpmath to see the exact 1/3 when it evaluates, such as `root`. 

This is a general gotcha with mpmath if you are working with dps higher than the default 15. You have to avoid implicitly computing things with Python floats, which always round to 15 digits.

**Comment by skirpichev** [comment]
Yeah, or could use mpmath's rationals (or builtin Fraction's), for example:
```
>>> import mpmath
>>> mpmath.mp.dps = 50
>>> mpmath.root(-8, 3, 0)
mpc(real='1.0', imag='1.7320508075688772935274463415058723669428052538103806')
>>> mpmath.power(-8, mpmath.mp.mpq(1, 3))
mpc(real='1.0', imag='1.7320508075688772935274463415058723669428052538103783')
```
c.f. Mathematica:
```
Wolfram Language 12.2.0 Engine for Linux x86 (64-bit)
Copyright 1988-2021 Wolfram Research, Inc.

In[1]:= N[Power[-8, 1/3], 50]

Out[1]= 1.0000000000000000000000000000000000000000000000000 + 
1.7320508075688772935274463415058723669428052538104 I
```
> It gives exact 1. for real part, but not exact Sqrt[3] for imaginary part. I did write to them also.

Hmm, so far, I can't see something wrong with the last answer.  It seems to be correct for 50 digits (up to `3810`).

**Comment by skirpichev** [comment]
btw, float's issue seems to be documented: https://mpmath.org/doc/current/basics.html#providing-correct-input

You can also create exponent from the string:
```
>>> mpmath.power(-8, mpmath.mpf('1/3'))
mpc(real='1.0', imag='1.7320508075688772935274463415058723669428052538103783')
```

**Comment by metelev-sv** [comment]
Thank you for answers!

In mathematica I use WolframAlpha, call
SetPrecision[Exp[Log[-8]/3.], 50] and get
1.0000000000000000000000000000000000000000000000000 + 1.7320508075688769711319991984055377542972564697266 I
which is differ from your answer. Now I understand, that it is because of -8 without point.

**Comment by skirpichev** [comment]
Ok, then #588 should fix this issue.  Let me know if you do think that https://mpmath.org/doc/current/basics.html#providing-correct-input should be rewritten/expanded.
