### ISSUE TITLE
The difference between using "for loop" and "matrix multiplication"?

### ISSUE THREAD

**Issue by jiangtong1000** [mpmath/mpmath#593]
Hi, I was just wondering what's the difference between using "for loop" and "matrix multiplication"? I mean, the precision. It was once found that by controlling the `mp.prec=64`, the "for loop" behaves much worse than using "matrix multiplication". thx.

**Comment by jiangtong1000** [comment]
it was a bit too long that I can't remember the case actually, thanks for your reply. You may close this issue.

**Comment by skirpichev** [comment]
Well, you can see [here](https://github.com/mpmath/mpmath/blob/98c48faf58286cd648deeb10e3295670f7aa878d/mpmath/matrices/matrices.py#L580-L583) how the multiplication is implemented:
```python
            for i in range(self.__rows):
                for j in range(other.__cols):
                    new[i, j] = self.ctx.fdot((self_get((i,k), self_zero), other_get((k,j), other_zero))
                                     for k in range(other.__rows))
```
mp.fdot uses mpf_sum to compute dot product and this is not a simple for loop (like math.fsum)...

Or this can be just another instance of #657...

Feel free to reopen this with more details, we can't guess.
