### ISSUE TITLE
Issue converting strings with _ to mpf

### ISSUE THREAD

**Issue by oscargus** [mpmath/mpmath#613]
From Python 3.7 it is possible to use _ in strings converted to floats (and maybe other types), so `float('1_2.3_4')` is valid and gives 12.34.

This causes a problem when converting this type of numbers using `from_str` or more exactly here:
https://github.com/fredrik-johansson/mpmath/blob/c11db84b3237bd8fc6721f5a0c5d7c0c98a24dc1/mpmath/libmp/libmpf.py#L1303-L1306

Should be solved by replacing `parts[1].rstrip('0')` with `parts[1].rstrip('0').replace('_', '')`.

**Comment by skirpichev** [comment]
Actually, this will be a violation of [PEP 515](https://www.python.org/dev/peps/pep-0515/).  But see [this](https://bugs.python.org/issue44267) and [this](https://github.com/aleaxit/gmpy/commit/ec8dabff9730b753f38647fb5af0c4bad7b492cb).
