### ISSUE TITLE
plot the Riesz function 

### ISSUE THREAD

**Issue by larous25** [mpmath/mpmath#615]
Hello, I want to plot the [Riesz function](https://en.wikipedia.org/wiki/Riesz_function)
And this is what I've done, I don't know if it's okay
```
import mpmath as mp 
Riesz = lambda z: mp.nsum(lambda n: ((-1)**(n+1) * (-z)**n) / (mp.fac(n-1)*mp.zeta(2*n)), [1, mp.inf])
```
sorry if this is not an appropriate place

**Comment by aassaa110012** [comment]
> Hello, I want to plot the [Riesz function](https://en.wikipedia.org/wiki/Riesz_function)
> 
> And this is what I've done, I don't know if it's okay
> 
> ```
> 
> import mpmath as mp 
> 
> Riesz = lambda z: mp.nsum(lambda n: ((-1)**(n+1) * (-z)**n) / (mp.fac(n-1)*mp.zeta(2*n)), [1, mp.inf])
> 
> ```
> 
> sorry if this is not an appropriate place

**Comment by skirpichev** [comment]
According to the quoted definition it rather should be:
```python
>>> from mpmath import nsum, fac, zeta, inf, plot
>>> riesz = lambda z: -nsum(lambda n: ((-z)**n) / (fac(n-1)*zeta(2*n)), [1, inf])
>>> plot(riesz, [0, 50])
```
I got this, which is close to the source:
![Figure_1](https://github.com/mpmath/mpmath/assets/2155800/dde15cba-f47f-402f-9c74-0772ff718186)
