### ISSUE TITLE
Update release to contain PR #570 

### ISSUE THREAD

**Issue by tazitoo** [mpmath/mpmath#616]
Can you make an updated release that contains PR #570?

Our [library ](https://github.com/capitalone/synthetic-data) has a dependency on mpmath  and our vuln scans fail because the current release does not contain the already merged fix in  #570.  Tagging @rreilly10  to keep him in the loop.

**Comment by skirpichev** [comment]
see #550

**Comment by tazitoo** [comment]
Issue #550 seems to deal with long term strategic maintenance.  This issue is short term tactical fix.  Or did I miss an implication that no releases will happen until that long term strategy is finalized?

**Comment by skirpichev** [comment]
> Issue #550 seems to deal with long term strategic maintenance.

Rather it's about there is no maintenance at all for now.

**Comment by skirpichev** [comment]
Fixed with 1.3
