### ISSUE TITLE
print value puzzles.

### ISSUE THREAD

**Issue by ztdepztdep** [mpmath/mpmath#617]
```
mp.pretty = True

mp.dps = 100
a=mp.mpf(1)/6
print(a)
b=mp.fdiv(1,6)
print(b)
print(mp.mpf(2)**32582657 - 1)
print(mp.mpf(10) ** (10**100))
```

It give me the following output:

```
0.166666666666667

0.166666666666667
1.24575026015369e+9808357
1.0e+10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

why the first and the second one give so little digits, i think it should has at leat 99 digits.
Could you please help me out.

Edit: correct formatting of example/output // @skirpichev

**Comment by ztdepztdep** [comment]
> This works for me. Maybe you had a typo somewhere?
> 
> ```
> >>> from mpmath import mp
> >>> mp.pretty = True
> >>> mp.dps = 100
> >>> a=mp.mpf(1)/6
> >>> print(a)
> 0.1666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667
> >>> print(mp.mpf(2)**32582657 - 1)
> 1.245750260153694554008555015747995031227959851511518428436704756625911152359973973805597596066168459e+9808357
> ```

Hi, I tried again. it still can't work. I run it in spyder in anaconda environment , and the version is 1.2.1.

**Comment by oscarbenjamin** [comment]
I just tried this with 1.2.1 in spyder and it worked fine. I tried with the code in the editor window or in the console window and both cases worked.

Are you sure that you ran the exact same code that was shown?

**Comment by skirpichev** [comment]
Ok, I think I'm able to reproduce that "issue".  Seems to be yet another instance of #657:
```python
>>> import mpmath as mp
>>> mp.pretty = True
>>> mp.dps = 100
>>> a=mp.mpf(1)/6
>>> print(a)
0.166666666666667
>>> b=mp.fdiv(1,6)
>>> print(b)
0.166666666666667
>>> print(mp.mpf(2)**32582657 - 1)
1.24575026015369e+9808357
>>> print(mp.mpf(10) ** (10**100))
1.0e+10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
@ztdepztdep, your original example miss the import statement.  Are you sure, that you do mpmath import as it is [suggested in the documentation](https://mpmath.org/doc/current/basics.html#basic-usage) and in above examples from @oscarbenjamin and @fredrik-johansson?
I.e. you must import mpmath like that:
```python
>>> from mpmath import mp
```
Not like that:
```python
>>> import mpmath as mp
```
Could you reproduce your issue with *first* variant?
