### ISSUE TITLE
accuracy of log

### ISSUE THREAD

**Issue by dowkeruk** [mpmath/mpmath#632]
I am a new user and have a simple query.

Why does log(1/5), say, not compute to full accuracy while log(5) does?

**Comment by asmeurer** [comment]
`1/5` evaluates to a Python float before mpmath has a chance to see it, which is only accurate to 15 digits. You should instead write something like `mpmath.mpf(1)/5`. This will evaluate 1/5 to the current precision.

```py
>>> mpmath.mp.dps = 100
>>> mpmath.mpf(1)/5
mpf('0.2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004')
>>> mpmath.log(1/5)
mpf('-1.60943791243410031908960810196836215908797345951612752271451999257795671201411705490872167697919241826')
>>> mpmath.log(mpmath.mpf(1)/5)
mpf('-1.609437912434100374600759333226187639525601354268517721912647891474178987707657764630133878093179610801')
>>> mpmath.log(5)
mpf('1.609437912434100374600759333226187639525601354268517721912647891474178987707657764630133878093179610801')
```

(side note: this has come up several times with different users. Perhaps mpmath should have a short "gotchas" page in the docs about this, similar to the [one in the SymPy docs](https://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and)).

**Comment by skirpichev** [comment]
Actually, this is documented [here](https://mpmath.org/doc/current/basics.html#providing-correct-input).  The fact that `1/5` evaluates to a Python float is a more basic thing, I'm not sure it worth a note.
@fredrik-johansson, or does it make sense for you?  We can add an example in the same section.
@asmeurer, "gotchas" page does make sense for me, if we can fill it with more then one case.  Any other suggestions?

**Comment by asmeurer** [comment]
I guess there's also this gotcha https://github.com/mpmath/mpmath/issues/657 (although I don't see why there needs to be multiple gotchas in order to document this).

**Comment by asmeurer** [comment]
How was this fixed by #670? I don't see anything in the docs that were added there about this.

**Comment by cbm755** [comment]
I figured it was covered by this change:

![image](https://user-images.githubusercontent.com/818622/229250323-4adc2238-897e-459f-a792-d9dc77745eec.png)

**Comment by asmeurer** [comment]
A single comment buried somewhere in a code example isn't exactly a useful guide for this. I was expecting something more along the lines of a full "gotchas" page that outlined this, why it happens, and how to avoid it (similar to the "gotchas" page in the SymPy docs). Not to mention the fact that this only covers a subset of the problem here (*any* Python float has this issue, not just ones created by integer division).

**Comment by cbm755** [comment]
Fair enough, although it is on the "Basic Usage", the first thing after installation...   https://mpmath.org/doc/current/basics.html

Shall we open a new bug to make that more obvious, add a "gotchas page"?

**Comment by skirpichev** [comment]
> How was this fixed by https://github.com/mpmath/mpmath/pull/670? I don't see anything in the docs that were added there about this.

Just for record, [this commit](https://github.com/mpmath/mpmath/pull/670/commits/b2301fbabeb21b4e480821c1a4771d7af196cd99).

Ok, lets reopen this with hope anyone will come with a better solution.

> A single comment buried somewhere in a code example

Seems fine for me in this case.  Just a quick note, where is appropriate, with an assumption that the reader is familiar with the language.

> Not to mention the fact that this only covers a subset of the problem here (any Python float has this issue, not just ones created by integer division).

In fact the whole section ("Providing correct input") was about it.

**Comment by cbm755** [comment]
oops sorry @skirpichev crossed paths.  Feel free to close mine and leave this one if you wish.

**Comment by skirpichev** [comment]
No, let's close this instead.  Your issue has enough context and a better title.
