### ISSUE TITLE
`polygamma()` evaluation hangs at certain precs

### ISSUE THREAD

**Issue by Parcly-Taxel** [mpmath/mpmath#647]
This issue was discovered during fuzz-testing for the generalised Euler function [here](https://github.com/sympy/sympy/pull/23926#issuecomment-1238519022).

@oscarbenjamin said:
> It seems that this hangs:
> 
> ```python
> euler(-1, -1+I).evalf()
> ```

I quickly traced the problem to this minimal example. The following code hangs in _pure mpmath_, with or without `gmpy2` installed:
```python
from mpmath import mp
mp.prec = 42
mp.polygamma(0, -0.5+0.5j)
```

----

By the way @fredrik-johansson you should implement the generalised Bernoulli and Euler functions and generalised (to complex arguments) harmonic numbers and polygamma function in mpmath. They have all landed in the latest development version of downstream SymPy.

**Comment by skirpichev** [comment]
@Parcly-Taxel, I can't reproduce problem on your example (with or without gmpy2):
```
>>> from mpmath import mp
>>> mp.prec = 42
>>> mp.polygamma(0, -0.5+0.5j)
mpc(real='0.131892637354523', imag='2.44065951997751')
```

**Comment by skirpichev** [comment]
Wait.  Lets make sure the problem was fixed and there is a regression test.
