### ISSUE TITLE
Tests shouldn't end up within the wheel.

### ISSUE THREAD

**Issue by KOLANICH** [mpmath/mpmath#671]

**Comment by skirpichev** [comment]
I guess, you think we shouldn't include tests to the distributed wheel.  But why not?
```
$ du -sch mpmath/
2.1M    mpmath/
2.1M    total
$ du -sch mpmath/tests
504K    mpmath/tests
504K    total
```
Not too big.  And users can test installed package with our standard test suite (it's documented).  Other packages from the Python scientific ecosystem also include tests, e.g. numpy.  So, I don't think something like a separate package for tests does make sense.
But feel free to reopen the issue and argue your opinion (or if I misunderstood you somehow).
