### ISSUE TITLE
ensure "gotchas" are easy to find and link to

### ISSUE THREAD

**Issue by cbm755** [mpmath/mpmath#677]
This section has some important "gotchas", in particular the impossibility of getting extra precision from a float:

https://mpmath.org/doc/current/basics.html#providing-correct-input

Current docs: https://mpmath.readthedocs.io/en/latest/basics.html#providing-correct-input
// edit by @skirpichev 

@asmeurer  suggested:

> Perhaps mpmath should have a short "gotchas" page in the docs about this, similar to the [one in the SymPy docs](https://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and)).

See #632 for a discussion and #670 for some recent changes.

**Comment by asmeurer** [comment]
As I mentioned in the issue another "gotcha" that can be mentioned is the misuse of `mpmath.dps` vs. `mpmath.mp.dps` (although personally I think we should just find a way to technically fix that problem).

**Comment by skirpichev** [comment]
> https://mpmath.org/doc/current/basics.html#providing-correct-input

In fact, this is only a brief description.  See also:
https://mpmath.org/doc/current/technical.html#decimal-issues

As I've mentioned in https://github.com/mpmath/mpmath/issues/632, I don't think there is something to do.

> "import mpmath as mp" ... although personally I think we should just find a way to technically fix that problem

Yes, I feel same.  This "gotcha" actually happens only for people who don't read documentation at all.

**Comment by asmeurer** [comment]
> This "gotcha" actually happens only for people who don't read documentation at all.

It's not even documented yet (that's the whole point of this issue), but regardless, this is the sort of toxic attitude that got you banned from the sympy community. If something is a common problem that people are running into, it should be fixed.

**Comment by skirpichev** [comment]
> this is the sort of toxic attitude that got you banned from the sympy community

Feel free to ask Fredrik to do same, if you think it does make sense.

Sorry, but I don't have a better explanation for #657 (and linked issues).

> If something is a common problem that people are running into, it should be fixed.

And there is an issue for this.  My point is that there is nothing to fix in the documentation: it suggests correct import statements.  With this in mind I would prefer more "technical" approach here (i.e. a warning or, better, an exception).

**Comment by cbm755** [comment]
Let's keep this civil.

We all agree a technical solution is best for #657.  I recall hitting this myself and feeling uncertain/nervous about how to import mpmath as result.  Its certainly worth fixing.

**Comment by skirpichev** [comment]
FYI: description was updated with a link to dev docs.

**Comment by skirpichev** [comment]
Let's keep this for a while, say for year, in case someone will came with a better solution.

**Comment by skirpichev** [comment]
#716 is another potential candidate for the gotchas section, if we will not alter default CPython limits (but, I think, we should).

**Comment by skirpichev** [comment]
> Let's keep this for a while, say for year, in case someone will came with a better solution.

Just a gentle reminder if someone would like to propose a patch.  @asmeurer? ;-)

So far we have few candidates for new "gotchas" section:
1. incorrect setting of prec/dps on the mpmath module, https://github.com/mpmath/mpmath/issues/657
2. int<->str conversion limits, https://github.com/mpmath/mpmath/issues/716
3. the given issue with true division behaviour

1st and 2nd issues are fixed.  (See #767 as a better alternative to the 2nd issue.)

**Comment by skirpichev** [comment]
Ok, no better variants were presented.
