### ISSUE TITLE
Update version in the master branch after a release?

### ISSUE THREAD

**Issue by WarrenWeckesser** [mpmath/mpmath#682]
Version 1.3.0 was released March 7 (thanks!), but the version string in the master branch (in [`mpmath/__init__.py`](https://github.com/mpmath/mpmath/blob/master/mpmath/__init__.py)) is still `1.3.0`.  Could `__version__` be updated to something like `1.4.0.dev0`?  Or something fancier that includes the git SHA in the version?  I don't have a preference for which convention to use, but anything that distinguishes a master branch installation from a released version would be helpful.

**Comment by skirpichev** [comment]
I would prefer "something fancy", i.e. setuptools_scm, not manual updates...  This is an official pypa project.

But see #586 and #443.  Not sure if this is relevant, however: it has no deps on the pkg_resources/packaging anymore and also we don't support py2.
