### ISSUE TITLE
ellipe function: wrong answer

### ISSUE THREAD

**Issue by FeelUsM** [mpmath/mpmath#708]
I call `ellipe(0.5)` and I get `1.350643881047`
[Here](https://keisan.casio.com/exec/system/1180573458) I set argument 0.5 and I get `1.46746220933942715546`
Values for other arguments also are strange.

version of library: 1.2.1

**Comment by skirpichev** [comment]
> I call ellipe(0.5) and I get 1.350643881047
> [Here](https://keisan.casio.com/exec/system/1180573458) I set argument 0.5 and I get 1.46746220933942715546

That's expected:
```
>>> mpmath.ellipe('0.25')
mpf('1.4674622093394272')
```

Please note the difference in the [definition of ellipe](https://mpmath.org/doc/current/functions/elliptic.html?highlight=ellipe#mpmath.ellipe), which is used by mpmath (or the Mathematica, [for example](https://reference.wolfram.com/language/ref/EllipticE.html)) and in your tool.
