### ISSUE TITLE
Hash for mpf(0.) and mpc(0.,0.) are equal

### ISSUE THREAD

**Issue by mmatera** [mpmath/mpmath#714]
Hi, 
Using `functools.lru_cache` I found that the hashes for this two different representations of 0. are the same, which produces some weird behaviour in my code. Is this behaviour set intentionally?

**Comment by skirpichev** [comment]
FYI:
```
>>> float(0)
0.0
>>> hash(_)
0
>>> complex(0, 0)
0j
>>> hash(_)
0
```

Lets keep this for a while in case someone will comment, but I don't see here something wrong.

**Comment by asmeurer** [comment]
Not just hashes, but any `mpf(x)` and `mpc(x, 0)` are equal

```py
>>> mpmath.mpf(1.) == mpmath.mpc(1., 0.0)
True
```

It does mean that lru_cache and dictionaries in general won't be able to distinguish them.

**Comment by skirpichev** [comment]
> Not just hashes, but any mpf(x) and mpc(x, 0) are equal

Indeed, this is an issue.

**Comment by skirpichev** [comment]
On another hand...

```
>>> float(0.0) == complex(0.0, 0.0)
True
>>> float(1.0) == complex(1.0, 0.0)
True
```

> It does mean that lru_cache and dictionaries in general won't be able to distinguish them.

So, the question is do we want to distinguish them?  Probably, not, at
least for compatibility with the Python numeric tower.

BTW, for the lru_cache this could be workarounded with the typed kwarg.

**Comment by skirpichev** [comment]
Ditto for gmpy2 types:
```
>>> gmpy2.mpfr(0.0) == gmpy2.mpc(0.0, 0.0)
True
>>> gmpy2.mpfr(1.0) == gmpy2.mpc(1.0, 0.0)
True
```

**Comment by mmatera** [comment]
Thank you for look at this and the feedback!

**Comment by asmeurer** [comment]
If mpmath already works this way it's probably worth keeping it, but FWIW, emulating the native Python types in this regard is often ill advised and can lead to more issues than if the distinct types were actually distinct. 

In general, the Python numeric tower is not actually a good design that should be emulated, especially for mathematical libraries where precision about types matters. For instance, according to [PEP 484](https://peps.python.org/pep-0484/), `float` is a subtype of `int`. That's often practically useful, but not actually a good idea for a library that is trying to be mathematically precise. It's an even bigger issue for libraries like NumPy where the actual machine type of a numeric value matters a lot. See also https://github.com/beartype/numerary.

See for example https://github.com/sympy/sympy/pull/20033 and https://github.com/sympy/sympy/issues/11707 for how this specific design decision (making different numeric types equal to each other) has caused issues in SymPy.

**Comment by skirpichev** [comment]
> float is a subtype of int

This looks odd only because the [PEP 3141](https://peps.python.org/pep-3141/) was inspired by the Scheme numeric tower, but it lacks the notion of exact/inexact number.  But here
both types are inexact.

Second, strongly speaking - above equality relations aren't part of the PEP.  In principle,
we could make ``mpf(1) != mpc(1, 0)``.  But I doubt it's a good idea:
1. this will be a context-dependent behaviour
2. introduce an incompatibility wrt gmpy2.mpfr/mpc
3. it doesn't make sense (well, for me) from a mathematical point of view

> has caused issues in SymPy

I don't think that quoted issues/pr are related directly to this issue.  We should
also keep in mind there is no atomic complex expressions in the SymPy (c.f. WMA Complex).
So, in this case it might make sense to have `0.0*I != 0.0` (i.e. as structurally
different expressions).

**Comment by skirpichev** [comment]
> I could handle it by using the typed keyword parameter of lru_cache

That's expected and was suggested above.  But could you explain why `mpf(0)==mpc(0,0)`
poses a problem for the Mathics at all?  BTW, `Complex[0.0, 0.0] == 0.0` is True in
the Wolfram Language (13.3.0 Engine).

**Comment by mmatera** [comment]
The problem was the LRU cache, not in the comparisons (which is handled without converting the numbers). From my side,  I think this issue can be closed.

**Comment by oscarbenjamin** [comment]
This is a general problem in Python that comes back to `1 == 1.0` being true and then `==` being the operator that is used for sets, dicts, lists etc. Ideally there would be a separate equality operator like `A === B` for testing that two objects are literally interchangeable. Then you could have `1 == 1.0` be True but `1 === 1.0` be False and also you could use this  other equality operator for all of Python's data structures.

Without having a separate equality operator there is always a tension in the defining the behaviour of `__eq__` and it is not possible to satisfy the different things that many people would expect `A == B` to do at the same time as getting sane behaviour and good performance from things like sets and dicts.

This is almost certainly not going to change in Python itself so we just have to accept that there is a potential trap that needs to be avoided any time we define equality for objects that are not literally interchangeable e.g.:
```python
In [1]: {1, 1.0}.pop().bit_length()
Out[1]: 1

In [2]: {1.0, 1}.pop().bit_length()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 {1.0, 1}.pop().bit_length()

AttributeError: 'float' object has no attribute 'bit_length'
```
Many of these sorts of problems could be helped through static type checking: it is usually a bad idea to have a set that contains a mix of ints and floats in the first place. Likewise maybe the function that is wrapped by `lru_cache` should really be defined to always have mpf args or always have mpc args or to take some object that wraps the two possibilities together in a well defined type.

Unfortunately PEP 484 already corrupted the use of type checking here by declaring that int is a subtype of float.

**Comment by mmatera** [comment]
> This is a general problem in Python that comes back to `1 == 1.0` being true and then `==` being the operator that is used for sets, dicts, lists etc. Ideally there would be a separate equality operator like `A === B` for testing that two objects are literally interchangeable. Then you could have `1 == 1.0` be True but `1 === 1.0` be False and also you could use this other equality operator for all of Python's data structures.
> 
> Without having a separate equality operator there is always a tension in the defining the behaviour of `__eq__` and it is not possible to satisfy the different things that many people would expect `A == B` to do at the same time as getting sane behaviour and good performance from things like sets and dicts.
> 
> This is almost certainly not going to change in Python itself so we just have to accept that there is a potential trap that needs to be avoided any time we define equality for objects that are not literally interchangeable e.g.:
> 
> ```python
> In [1]: {1, 1.0}.pop().bit_length()
> Out[1]: 1
> 
> In [2]: {1.0, 1}.pop().bit_length()
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[2], line 1
> ----> 1 {1.0, 1}.pop().bit_length()
> 
> AttributeError: 'float' object has no attribute 'bit_length'
> ```
> 
> Many of these sorts of problems could be helped through static type checking: it is usually a bad idea to have a set that contains a mix of ints and floats in the first place. Likewise maybe the function that is wrapped by `lru_cache` should really be defined to always have mpf args or always have mpc args or to take some object that wraps the two possibilities together in a well defined type.
> 
> Unfortunately PEP 484 already corrupted the use of type checking here by declaring that int is a subtype of float.

I guess that just adding a comment in the documentation would be enough to avoid this confusion.

**Comment by skirpichev** [comment]
> The problem was the LRU cache, not in the comparisons

I think, that's related.  For equal hashes we fallback to comparisons, and we have equal
hashes even for very simple objects:
```
>>> hash(-2)
-2
>>> hash(-1)
-2
```
Same hashes for different entities is a fine (but unfortunate) story.

BTW:
```
$ wolframscript 
Wolfram Language 13.3.0 Engine for Linux x86 (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.

In[1]:= Complex[0.0, 0.0] == 0.0

Out[1]= True
```

> I think this issue can be closed.

I think so.

> Then you could have 1 == 1.0 be True but 1 === 1.0 be False

I think it's a good tradeoff: if you want strict equality testing - check types.

> function that is wrapped by lru_cache should really be defined to always have mpf args or always have mpc args

Or your can use types kwargs.
