### ISSUE TITLE
Document/(disable?) new int/str conversions limits (in CPython 3.11+ and older bugfix releases)

### ISSUE THREAD

**Issue by skirpichev** [mpmath/mpmath#716]
See https://github.com/sympy/sympy/issues/24033

This will hit at least ``from_str()/to_str()`` functions, but maybe more...

The gmpy2 backend doesn't have this "feature".  So, as an alternative - we could disable this with ``sys.set_int_max_str_digits(0)`` in the ``__init__.py``.  But we should warn users somehow: their code might rely on this new behaviour.

**Comment by oscarbenjamin** [comment]
> So, as an alternative - we could disable this with `sys.set_int_max_str_digits(0)` in the `__init__.py`

I don't recommend disabling it because then mpmath will get another CVE. Core Python has declared that this feature is needed for security so any library that disables it will be considered insecure.

**Comment by skirpichev** [comment]
I doubt the mpmath could be considered usable without gmpy2.  With this use case it will vulnerable to this kind of DoS attacks anyway.

More strong reason against: there is no mechanism to revert this "feature" per library/module.

I'm thinking about the new kwarg for `int()` to override this settings per constructor call (with precedence over global setup).

**Comment by oscarbenjamin** [comment]
> I'm thinking about the new kwarg for `int()` to override this settings per constructor call (with precedence over global setup).

I agree that the fix here needs to be some change in CPython. The global setting is broken.

New functions should be added but the problem also is that these things are called indirectly by other functions:
```python
In [4]: l = [math.factorial(5000)]

In [5]: str(l)
---------------------------------------------------------------------------
ValueError 
```
It is not clear what is a clean way to override this given that both `__repr__` and `__str__` have been hobbled.

**Comment by skirpichev** [comment]
Yeah, that part of "feature" doesn't in my head.

I've seen some examples (like "online calculator") in the d.p.o thread you have started (hooray, I've time to read it!), but there is no enlightenment yet...  Usually, we add restrictions for *input* data to mitigate this kind of issues.  Then why this limitation exists also for `str()` (and not for multiplication or ``pow`` as well)?

**Comment by asmeurer** [comment]
My take here is the same as https://github.com/sympy/sympy/issues/24033#issuecomment-1242298224. We should just leave it as it is and point people to upstream if they run into it. And I agree with Oscar. Despite what the core devs have stated in that issue, I expect that just disabling it in `__init__.py` would lead to a CVE or something like that. 

If there is some internal algorithm in mpmath that uses str() (other than the obvious from/to_str) it could be disabled for just that algorithm. I'm guessing there aren't any though.

**Comment by skirpichev** [comment]
> I expect that just disabling it in __init__.py would lead to a CVE or something like that.

Lets just ask them.  I feel this case worth a FAQ entry at least.

**Comment by skirpichev** [comment]
Ok, maybe they will answer someday.  Meanwhile I'll add a warning in the sphinx docs (see  #731).  Let me know if you think this is not enough to solve the issue.

Probably, the only place which this affects - the ``str_to_man_exp()`` function.  I.e. ``to_str()`` is *not* affected.  An example:
```pycon
>>> mpmath.mpf('1' * 500_000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 67, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 74, in mpf_convert_arg
    if isinstance(x, str): return from_str(x, prec, rounding)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/libmp/libmpf.py", line 1229, in from_str
    man, exp = str_to_man_exp(x, base)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/libmp/libmpf.py", line 1196, in str_to_man_exp
    x = MPZ(int(x, base))
            ^^^^^^^^^^^^
ValueError: Exceeds the limit (4300 digits) for integer string conversion: value has 500000 digits; use sys.set_int_max_str_digits() to increase the limit
```
As you can see, this affects *all* backends.  Probably, we should change to ``MPZ(x, base)`` instead.  The only problem is https://github.com/aleaxit/gmpy/issues/381, which I think could be workarounded.
