### ISSUE TITLE
AttributeError: 'FPContext' object has no attribute 'zetazero'

### ISSUE THREAD

**Issue by Kronuz** [mpmath/mpmath#718]
Regarding this line in `mpmath/functions/functions.py`, where does that `self.zetazero` come from?:

```py
class SpecialFunctions(object):
    ...
    def __init__(self):
        ...
        self.zetazero_memoized = self.memoize(self.zetazero)
```

https://github.com/mpmath/mpmath/commit/c58dc54a74117d538057ba4dbf50ee78a6baf74f#diff-4a3b83d9c86871fb9764fc1fdc3c1af39e3e7a631144149e8871c7dfce4d82d1R56

I ask because I've hit a way I'm seeing:

```
  File "sympy/__init__.py", line 22, in <module>
    import mpmath
  File "mpmath/__init__.py", line 9, in <module>
    fp = FPContext()
  File "mpmath/ctx_fp.py", line 19, in __init__
    StandardBaseContext.__init__(ctx)
  File "mpmath/ctx_base.py", line 45, in __init__
    SpecialFunctions.__init__(ctx)
  File "mpmath/functions/functions.py", line 58, in __init__
    self.zetazero_memoized = self.memoize(self.zetazero)
AttributeError: 'FPContext' object has no attribute 'zetazero'
```

cc: @ariasdereyna

**Comment by skirpichev** [comment]
On which version you have seen this?

In the current master:
```
>>> import mpmath
>>> mpmath.mp.zetazero
<bound method zetazero of <mpmath.ctx_mp.MPContext object at 0x7faac66b6a10>>
>>> mpmath.fp.zetazero
<bound method zetazero of <mpmath.ctx_fp.FPContext object at 0x7faac6855510>>
```

**Comment by skirpichev** [comment]
Ok, please reopen if you know how to reproduce this.

Regarding to your question,

> Regarding this line in mpmath/functions/functions.py, where does that self.zetazero come from?

https://github.com/mpmath/mpmath/blob/2990ec6d10b3cb42dce8c11b82f3321d20dcedee/mpmath/functions/zetazeros.py#L341
