### ISSUE TITLE
problem with zeta

### ISSUE THREAD

**Issue by ariasdereyna** [mpmath/mpmath#723]
when I tried 

mp.dps=16
zeta(-0.01 + 1000j)

I get an ugly error 

SystemError                               Traceback (most recent call last)
/var/folders/d_/wxs08xwn6p93d68hl6xf6nb40000gn/T/ipykernel_1815/4123431181.py in <module>
      1 mp.dps=16
----> 2 zeta(-0.01 + 1000j)

/private/var/tmp/sage-9.6-current/local/var/lib/sage/venv-python3.10.3/lib/python3.10/site-packages/mpmath/functions/zeta.py in zeta(ctx, s, a, derivative, method, **kwargs)
    578     if ctx.re(s) > 2*ctx.prec and a == 1 and not derivative:
    579         return ctx.one + ctx.power(2, -s)
--> 580     return +ctx._hurwitz(s, a, d, **kwargs)
    581 
    582 @defun

/private/var/tmp/sage-9.6-current/local/var/lib/sage/venv-python3.10.3/lib/python3.10/site-packages/mpmath/functions/zeta.py in _hurwitz(ctx, s, a, d, **kwargs)
    593                 print("zeta: Attempting reflection formula")
    594             try:
--> 595                 return _hurwitz_reflection(ctx, s, a, d, atype)
    596             except NotImplementedError:
    597                 pass

/private/var/tmp/sage-9.6-current/local/var/lib/sage/venv-python3.10.3/lib/python3.10/site-packages/mpmath/functions/zeta.py in _hurwitz_reflection(ctx, s, a, d, atype)
    652     p += shift*q
    653     assert 1 <= p <= q
--> 654     g = ctx.fsum(ctx.cospi(t/2-2*k*b)*ctx._hurwitz(t,(k,q)) \
    655         for k in range(1,q+1))
    656     g *= 2*ctx.gamma(t)/(2*ctx.pi*q)**t

/private/var/tmp/sage-9.6-current/local/var/lib/sage/venv-python3.10.3/lib/python3.10/site-packages/sage/libs/mpmath/ext_main.pyx in sage.libs.mpmath.ext_main.Context.fsum (build/cythonized/sage/libs/mpmath/ext_main.c:10535)()
    763         workopts.rounding = ROUND_D
    764         unknown = global_context.zero
--> 765         sig_on()
    766         try:  # Way down, there is a ``finally`` with sig_off()
    767             MPF_init(&sre)

SystemError: calling remove_from_pari_stack() inside sig_on()

**Comment by skirpichev** [comment]
I can't reproduce this either on the 1.3.0 version or in the current master branch:
```
Python 3.10.11+ (heads/3.10:e277266a92, Apr 29 2023, 08:01:37) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> mp.dps=16
>>> zeta(-0.01 + 1000j)
mpc(real='-8.971459529241107012', imag='8.732179332810065198')
>>> import mpmath
>>> mpmath.__version__
'1.3.0'
```
Perhaps, this is specific for the sage backend.  Could you try setting the environment variable 'MPMATH_NOSAGE'?  Or test more recent sage version?

@ariasdereyna, please also describe your setup in more details.  E.g. it's not clear which mpmath version you are using.

BTW, Not sure if the mpmath repo is the right place to report this issue.  https://github.com/sagemath/sage/issues - seems to be a better, as it's clearly about the sage mpmath package.

**Comment by skirpichev** [comment]
@dimpase, could you please take look on this issue?  I think it's more suitable for the sage repo.

**Comment by dimpase** [comment]
I'll have  a look. Sage 9.6 is a vintage version, I must say.

**Comment by dimpase** [comment]
I can reproduce this in the Sage 10.2.beta5 shell:
```
SageMath version 10.2.beta5, Release Date: 2023-09-27              │
│ Using Python 3.11.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: from mpmath import *
sage: mp.dps=16
sage: zeta(-0.01 + 1000j)
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
Cell In [3], line 1
----> 1 zeta(-RealNumber('0.01') + ComplexNumber(0, '1000'))

File /usr/lib/python3.11/site-packages/mpmath/functions/zeta.py:580, in zeta(ctx, s, a, derivative, method, **kwargs)
    578 if ctx.re(s) > 2*ctx.prec and a == 1 and not derivative:
    579     return ctx.one + ctx.power(2, -s)
--> 580 return +ctx._hurwitz(s, a, d, **kwargs)

File /usr/lib/python3.11/site-packages/mpmath/functions/zeta.py:595, in _hurwitz(ctx, s, a, d, **kwargs)
    593     print("zeta: Attempting reflection formula")
    594 try:
--> 595     return _hurwitz_reflection(ctx, s, a, d, atype)
    596 except NotImplementedError:
    597     pass

File /usr/lib/python3.11/site-packages/mpmath/functions/zeta.py:654, in _hurwitz_reflection(ctx, s, a, d, atype)
    652 p += shift*q
    653 assert 1 <= p <= q
--> 654 g = ctx.fsum(ctx.cospi(t/2-2*k*b)*ctx._hurwitz(t,(k,q)) \
    655     for k in range(1,q+1))
    656 g *= 2*ctx.gamma(t)/(2*ctx.pi*q)**t
    657 v += g

File /mnt/opt/Sage/sage-dev/src/sage/libs/mpmath/ext_main.pyx:767, in sage.libs.mpmath.ext_main.Context.fsum()
    765 workopts.rounding = ROUND_D
    766 unknown = global_context.zero
--> 767 sig_on()
    768 try:  # Way down, there is a ``finally`` with sig_off()
    769     MPF_init(&sre)

SystemError: calling remove_from_pari_stack() inside sig_on()
sage: 
```

**Comment by dimpase** [comment]
In isolation from Sage, using the same Python and the same mpmath, everything is fine.
```
$ python3
Python 3.11.5 (main, Sep 16 2023, 22:27:40) [GCC 13.1.1 20230527] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> mp.dps=16
>>> zeta(-0.01 + 1000j)
mpc(real='-8.971459529241107012', imag='8.732179332810065198')
>>> 
```
but from Sage's venv, it's not:
```
$ ./sage --python
Python 3.11.5 (main, Sep 16 2023, 22:27:40) [GCC 13.1.1 20230527] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> mp.dps=16
>>> zeta(-0.01 + 1000j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/mpmath/functions/zeta.py", line 580, in zeta
    return +ctx._hurwitz(s, a, d, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mpmath/functions/zeta.py", line 595, in _hurwitz
    return _hurwitz_reflection(ctx, s, a, d, atype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mpmath/functions/zeta.py", line 654, in _hurwitz_reflection
    g = ctx.fsum(ctx.cospi(t/2-2*k*b)*ctx._hurwitz(t,(k,q)) \
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sage/libs/mpmath/ext_main.pyx", line 767, in sage.libs.mpmath.ext_main.Context.fsum
SystemError: calling remove_from_pari_stack() inside sig_on()
```

So it has to do with Sage vs no-Sage code path.

**Comment by dimpase** [comment]
it's not really a Sagemath issue, it's mpmath issue, of it doing something weird with Sagemath as a backend.

**Comment by ariasdereyna** [comment]
@dimpase and @skirpichev  thank you for your interest.  Sorry, but I am totally unfamiliar with these issues. I solved my problem by raising the mp.dps value.

I use sage 9.6 because it takes me to a comfortable environment in Jupyter but I open a Python document. I didn't know that I was using Sage anyway.

**Comment by dimpase** [comment]
It doesn't seem to matter whether it's Sage 9.6 or a later version. It's the problem of mpmath, it uses Sage in a rather crude way. It should not `import sage.all`, Sage, has finer ways to import really needed things nowadays.

**Comment by skirpichev** [comment]
> it's not really a Sagemath issue, it's mpmath issue, of it doing something weird with Sagemath as a backend.

@dimpase, thanks.  Sorry for my frustration - part of mpmath's bindings to Sage was in the sage repo...

> I solved my problem by raising the mp.dps value.

@ariasdereyna, how big it was?  I'm trying your workaround on https://sagecell.sagemath.org/, but it wasn't successful.  Could you show exact code you run (with import's, etc)?  Could you also show value of ``mpmath.libmp.BACKEND``.  I would guess you aren't use the sage backend now.

**Comment by dimpase** [comment]
we certainly have to solve this mpmath/sage mess in some way.

I wonder if this can be reproduced without sage, by using the defaults set in sage interface with mpmath.

**Comment by ariasdereyna** [comment]
@dimpase  
I tried to answer your question above. 
In my Jupyter page (that I start by open SageMath-9-6) I open a new document. And I run

from mpmath import *

libmp.BACKEND 
'sage'

Then I run 

mp.dps=16
zeta(-0.01 + 1000j)  

getting my error.   It is true that I solved my problem by putting mp.dps=20, but my problem was not with 
zeta(-0.01 + 1000j) , I was running a complicated program that have to compute some values of zeta.  The value -0.01 + 1000j  I compose to get a simple value and giving the error I had.  

mp.dps=20
zeta(-0.01 + 1000j)  

appear to give the same problem. 

Can I use Python in  Jupyter without sage?  I do not know how to do it.

**Comment by dimpase** [comment]
jupyter is a totally standard thing to install, system wide, or otherwise.

then, if needed, you can configure so that Sage's Jupyter kernel is available to it.

**Comment by dimpase** [comment]
OK, it's indeed a Sage bug - an improper use of sig_on/sig_off in Cython code interfacing mpmath. Fixing it makes the error disappear.

I'll post a link as soon as there is a PR with the fix.

**Comment by skirpichev** [comment]
I'll add a regression test.  We don't test sage backend yet (no idea how to solve #705), but it seems currently there are no tests, which could trigger this bug in Sage.

**Comment by skirpichev** [comment]
Sage PR: https://github.com/sagemath/sage/pull/36422
