### ISSUE TITLE
psi and digamma have limited precision

### ISSUE THREAD

**Issue by ribault** [mpmath/mpmath#729]
The precision of the functions psi and digamma seems not to exceed 20 digits, even when setting mp.dps = 100. In the example below, the precision is tested by computing combinations that should be zero due to relations between the functions at z and at z+1. In the output I would expect results of the order 10**(-100) but the actual results are not smaller than 10**(-20). 

----- Input ------

import mpmath
print('mpmath version:', mpmath.__version__)

from mpmath import mp, digamma, psi
mp.dps = 100

z = 1/9 + 7*1j
diff1 = psi(0, z+1) - psi(0, z) - 1/z
diff2 = digamma(z+1) - digamma(z) - 1/z
diff3 = psi(1, z+1) - psi(1, z) + 1/z**2
for diff in [diff1, diff2, diff3]: print("%.4g" % abs(diff))

---- Output ----

mpmath version: 1.3.0
2.171e-17
2.171e-17
3.172e-19

**Comment by ribault** [comment]
Oops sorry the issue seems to be because I entered the test number as z=1/9+7*1j instead of for example z=mp.mpc('.4', '.8'). There seems to be no issue in fact.

**Comment by oscarbenjamin** [comment]
I confirm that creating the mpc correctly solves the problem:
```python
In [4]: import mpmath
   ...: print('mpmath version:', mpmath.__version__)
   ...: 
   ...: from mpmath import mp, digamma, psi
   ...: mp.dps = 100
   ...: 
   ...: z = mp.mpc('1/9') + mp.mpc(7)*1j
   ...: diff1 = psi(0, z+1) - psi(0, z) - 1/z
   ...: diff2 = digamma(z+1) - digamma(z) - 1/z
   ...: diff3 = psi(1, z+1) - psi(1, z) + 1/z**2
   ...: for diff in [diff1, diff2, diff3]: print("%.4g" % abs(diff))#
mpmath version: 1.4.0a0
1.788e-102
1.788e-102
2.465e-103
```

**Comment by skirpichev** [comment]
``z = mp.mpf('1/9') + 7j`` should be enough.  I think, it's [well documented](https://mpmath.readthedocs.io/en/latest/basics.html#providing-correct-input) in docs (and we have https://github.com/mpmath/mpmath/issues/677).  So, I will close this.
