### ISSUE TITLE
What is the relationship between findroot and mp.dps?

### ISSUE THREAD

**Issue by finefoot** [mpmath/mpmath#736]
![XjwPn](https://github.com/mpmath/mpmath/assets/33361833/0c404b67-6214-4289-98a7-2ba72bf89909)

```python
from mpmath import *
y = lambda x: pi*(7.92e-24*x*(1 - exp(2.47376311844078e-6/x)) + 3.91844077961019e-30*exp(2.47376311844078e-6/x))/(x**7*(1 - exp(2.47376311844078e-6/x))**2)
```

I'm trying to find the root that is visible in the plot above close to 0.5e-6. However, `findroot` finds a different root:

```
>>> mp.dps = 15
>>> findroot(y, 0.5e-6, verbose=True)
x:     0.2500005
error: 0.25
mpf('0.2500005')
```

So, instead, I specify an interval, but I get an error:

```
>>> mp.dps = 15
>>> findroot(y, (0.4e-6, 0.6e-6))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/finefoot/.local/lib/python3.9/site-packages/mpmath/calculus/optimization.py", line 985, in findroot
    raise ValueError('Could not find root within given tolerance. '
ValueError: Could not find root within given tolerance. (1.21186214334073616909e-17 > 2.16840434497100886801e-19)
Try another starting point or tweak arguments.
```

However, I am successful with both a lower as well as a higher value for `mp.dps`:

```
>>> mp.dps = 10
>>> findroot(y, (0.4e-6, 0.6e-6))
mpf('4.982288428783e-7')
>>> mp.dps = 20
>>> findroot(y, (0.4e-6, 0.6e-6))
mpf('4.9822884287834956804705e-7')
```

How can this be explained? Unfortunately, the docs on root-finding and optimization https://www.mpmath.org/doc/current/calculus/optimization.html don't mention `mp.dps` at all.

Furthermore, if I enable `verbose=True` for the previous call with `mp.dps = 15`, it looks like the root was indeed found - despite what the error says:

```
>>> findroot(y, (0.4e-6, 0.6e-6), verbose=True)
x:     5.3578149929971142579e-7
error: 1.9999999999999999095e-7
x:     4.72164087189809447005e-7
error: 6.42185007002885470587e-8
x:     5.02383012597846992377e-7
error: 6.36174121099019787856e-8
x:     4.98641817056914280534e-7
error: 3.02189254080375453729e-8
x:     4.98221655157573724369e-7
error: 3.74119554093271184333e-9
x:     4.98228855137876342545e-7
error: 4.20161899340556164784e-10
x:     4.98228842878712985304e-7
error: 7.1999803026181755294e-12
x:     4.98228842878349568029e-7
error: 1.22591633572409451659e-14
x:     4.98228842878349568047e-7
error: 3.63417275350997737668e-19
x:     4.98228842878349568047e-7
error: 1.847827784389698053e-26
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/finefoot/.local/lib/python3.9/site-packages/mpmath/calculus/optimization.py", line 985, in findroot
    raise ValueError('Could not find root within given tolerance. '
ValueError: Could not find root within given tolerance. (1.21186214334073616909e-17 > 2.16840434497100886801e-19)
Try another starting point or tweak arguments.
```

**Comment by skirpichev** [comment]
> How can this be explained? Unfortunately, the docs on root-finding and optimization https://www.mpmath.org/doc/current/calculus/optimization.html don't mention mp.dps at all.

In fact, it does:
```
    Mathematically speaking, this function returns `x` such that
    `|f(x)|^2 \leq \mathrm{tol}` is true within the current working precision.
    If the computed value does not meet this criterion, an exception is raised.
```

It might be not clear, what's the default (tol=None) means.  From the code you could see:
https://github.com/mpmath/mpmath/blob/c5939823669e1bcce151d89261b802fe0d8978b4/mpmath/calculus/optimization.py#L905-L907
mp.eps is the epsilon of working precision.

Maybe this default should be documented.  Unfortunately, I doubt that an explicit default argument value is possible for the ``tol``.

**Comment by finefoot** [comment]
Thank you very much for your reply. I've since been diving a little deeper, trying to understand what happens.

So `tol` depends on `eps` which in turn depends on `dps`, right? And for `mp.dps = 15` I get the following error:

> `ValueError: Could not find root within given tolerance. (1.21186214334073616909e-17 > 2.16840434497100886801e-19)`

So it seems like `tol` is 2.16840434497100886801e-19. However:

```python
>>> mp.dps = 15
>>> mp.eps * 2 ** 10
mpf('2.2737367544323206e-13')
```

Then I found this curious line:

https://github.com/mpmath/mpmath/blob/c5939823669e1bcce151d89261b802fe0d8978b4/mpmath/calculus/optimization.py#L903-L903

Why is this there? I tried git blame to find out more. `@extraprec(20)` happened in ebe8a76e243c8a71bd457952376f48cbb431acf1 but only changed the value from 10 to 20. And `@extraprec(10)` was already there in b72093a5c7443b45c64cf232277855c7d5c60870 which introduced the `findroot` function. It's based on the `secant` function which contains something similar:

https://github.com/mpmath/mpmath/blob/b72093a5c7443b45c64cf232277855c7d5c60870/mpmath/calculus.py#L166-L166

But I couldn't find any explanations there, either. Why `ctx.prec += 20`? Why not `ctx.prec += 200` or `ctx.prec += 2000`? ;)

Anyway, even if I add 20, I still can't get the same value as `tol` from the error:

```python
>>> mp.dps = 15 + 20
>>> mp.eps * 2 ** 10
mpf('1.5407439555097886824447823540679418548e-33')
```

In conclusion, unfortunately, I still fail to understand why the solver succeeds with a lower precision 10 or higher precision 20, yet fails with specific precision 15. And it doesn't only happen for 15:

```python
>>> bad = []
>>> for dps in range(1, 1000):
...    try:
...        mp.dps = dps
...        findroot(y, (0.4e-6, 0.6e-6)) and None
...    except ValueError:
...        bad.append(dps)
... 
>>> bad
[1, 2, 3, 4, 5, 6, 7, 8, 9, 14, 15, 92, 95, 171, 370, 714]
```

Initially, I thought that maybe something similar to #339 might be the issue here, too. So I also tried increasing `maxsteps`:

> *maxsteps*
> after how many steps the solver will cancel

However, even if I set `maxsteps=1000`, `findroot` still only shows 10 steps done. So it seems like the default solver still cancels after 10 steps and ignores `maxsteps`. The argument seems to serve only as an upper limit in `findroot` to limit the number of iterations from the solver that will be considered?

**Comment by skirpichev** [comment]
> maxsteps after how many steps the solver will cancel

That's not quite accurate, actually.  Some solvers (like Newton or Bisection) return an infinite stream of data.  But some (including Secant) can terminate iteration, regardless of the ``maxsteps`` value: https://github.com/mpmath/mpmath/blob/b72093a5c7443b45c64cf232277855c7d5c60870/mpmath/optimization.py#L31-L46
