### ISSUE TITLE
Issue with High Precision Calculations Resulting in Scientific Notation

### ISSUE THREAD

**Issue by wanfuse123** [mpmath/mpmath#737]
Hello,

I'm experiencing an issue where calculations done using high precision (mp.dps = 9866) result in numbers being represented in scientific notation, which is causing issues in further computations.

Here is a simplified example of the problem:

# Set the precision to 20000 digits
mpmath.mp.dps = 20000

sys.set_int_max_str_digits(0)

import mpmath as mp

# Set high precision
mp.mp.dps = 9101

# Example calculation
number = mp.sqrt(mp.mpf('12345' + '0' * 9101))

# Print result
print(number)

I want to avoid scientific notation COMPLETELY

want to custom format the numbers with a function that seems to be working fine (function works)

thanks for the help!

**Comment by skirpichev** [comment]
@wanfuse123, please specify the mpmath version and actual output.  I see a huge number in a decimal notation (ie., like ``123.456``, not in scientific).

What do you get and what do you want?

**Comment by wanfuse123** [comment]
Need a doc or link how to get mpmath ( latest stable) on Ubuntu / Debian available through pip ( on phone not at computer , can reply later. Issue is either mpmath, python or bash issue or combination of above where numbers print out in scientific notation no matter what I do). Put this on pause for now,  will come back when I can with more details., thanks!

**Comment by skirpichev** [comment]
> Need a doc or link how to get mpmath ( latest stable) on Ubuntu / Debian available through pip

You can use documentation:
https://mpmath.readthedocs.io/en/latest/setup.html#using-pip

Set up a virtual environment before:
```
$ python3 -m venv path_to_venv
$ . path_to_venv/bin/activate
```

**Comment by wanfuse123** [comment]
thanks just close this for now, that was a brain dead reply on my account.
I meant to say need to find a document detailing how to work around
formatting issues on debian / ubuntu/python/ rust/ c in regards to avoiding
scientific notation and terminal and python / c rust limits in this regard.
I have waisted tons of time on this issue while everything else seems to
work great. I will come back to it in the near future and carefully
document my work arounds and findings, when i get some time.


regards,


steven
