### ISSUE TITLE
truncation of a number , returning it as a string or returning it as a number

### ISSUE THREAD

**Issue by wanfuse123** [mpmath/mpmath#739]
#!/usr/bin/env python3
import mpmath
import decimal
import contextlib

# Setting the default precision for mpmath
mpmath.mp.dps = 200  # equivalent to 100 decimal places

globally I want 200 digits of precision
for this function I want to truncate the number to 3 decimal places (not rounding)

number before truncation

1801756525298.9818269642473878415409030920144234765379598378285432587593595193280321340695380386754499734862985613643529020996450507965134591386414827276896738266661603236529275880652240986546102345926

desired number after truncation:
1801756525298.981

things I have tried
most produce errors

thanks in advance!
very much appreciated!

def truncate_to_3_decimals(number):
    number_str = mpmath.nstr(number)
    formatted_number = f"{number_str:.3f}"
    return formatted_number
    
def truncate_to_3_decimals_sav(number):
    return f"{number:.3f}"
    
def truncate_to_3_decimals_sav5(number):
    original_dps = mpmath.mp.dps
    mpmath.mp.dps = 3
    truncated_str = mpmath.nstr(number)
    mpmath.mp.dps = original_dps
    return mpmath.mpf(truncated_str)
    
def truncate_to_3_decimals_sav4(number):
    with contextlib.TemporaryPrecisionContext(3):
        truncated_str = mpmath.nstr(number)
        return truncated_str
    
def truncate_to_3_decimals_savc(number):
    number_str = str(number)
    truncated_number = decimal.Decimal(number_str)
    print("truncated_number *: ", truncated_number)
    return truncated_number
    
def truncate_to_3_decimals_sav2(number):

  # Convert to string
  number_str = str(number)
  print("number: ", number)
  print("number_str ", number_str)
  
  # Truncate string
  truncated_str = number_str[:number_str.find('.') + 4]
  print("truncated_str", truncated_str)
  
  # Convert back to mpmath number
  return mpmath.mpf(truncated_str)
  
def truncate_to_3_decimals_sav(number):
    # Convert the number to a string
    number_str = str(number)

    # Split the string into integer and fractional parts
    if '.' in number_str:
        integer_part_str, fractional_part_str = number_str.split('.')
    else:
        integer_part_str = number_str
        fractional_part_str = '0'

    # Ensure the fractional part has at least 3 characters (pad with zeros if needed)
    fractional_part_str = fractional_part_str.ljust(3, '0')

    # Truncate the fractional part to 3 decimal places
    truncated_fractional_part_str = fractional_part_str[:3]

    # Combine the integer and truncated fractional parts
    truncated_number_str = integer_part_str + '.' + truncated_fractional_part_str
    return mpmath.mpf(truncated_number_str)

**Comment by skirpichev** [comment]
> for this function I want to truncate the number to 3 decimal places (not rounding)

You can do that with rounding:
```pycon
>>> mpmath.nstr(a, 16)
'1801756525298.982'
```
or without:
```
>>> str(int(a))+mpmath.nstr(mpmath.frac(a))[1:5]
'1801756525298.981'
```
