### ISSUE TITLE
Implement directed rounding in to_str()

### ISSUE THREAD

**Issue by skirpichev** [mpmath/mpmath#757]
See #109.  Eventually, this could be used to support [gmpy2-like rounding modes](https://gmpy2.readthedocs.io/en/latest/mpfr.html#gmpy2.mpfr.__format__) in ``mpf/mpc.__format__()``.

**Comment by javierelpianista** [comment]
Is the `mpf.__format__()` method in the works?

**Comment by skirpichev** [comment]
No.  See also https://github.com/mpmath/mpmath/issues/337.

**Comment by skirpichev** [comment]
Probably, rounding in to_str() could be added, based on #823.

**Comment by skirpichev** [comment]
> The obvious solution is to implement both kinds of tying and add them as an additional argument to to_str (asides from the rounding).

An additional argument appears anyway (to specify rounding mode in to_str()).  We will have just different defaults (for now) in to_str() and round_digits().

> Maybe for a future PR? After rounding types

That definitely should be after adding support for rounding in format().
