### ISSUE TITLE
setup.py lacks shebang

### ISSUE THREAD

**Issue by vks** [mpmath/mpmath#77]
bc.. $ ./setup.py install  
./setup.py: line 1: from: command not found  
: command not found  
'/setup.py: line 3: syntax error near unexpected token `name='mpmath',
'/setup.py: line 3:`setup(name='mpmath',  
$ python setup.py install
running install  
running build  
running build_py 
[...]                               

This is trivial, simple #!python in the first line would do the job.

p. Original issue for "#77":https://github.com/fredrik-johansson/mpmath/issues/77: "http://code.google.com/p/mpmath/issues/detail?id=37":http://code.google.com/p/mpmath/issues/detail?id=37

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by skirpichev** [comment]
I think this is fixed.
