### ISSUE TITLE
Manual zeta of Riemann diverges of "manual" implementation

### ISSUE THREAD

**Issue by bpmsilva** [mpmath/mpmath#784]
I want to compute the segments of the zeta function, this cannot be directly done through the mpmath.zeta function. I manually implemented the function, but it does not converge for the "first" zero of zeta. Why? Is the computation precision wrong?

```
# %% Imports
import mpmath

# %% Constants
mpmath.mp.dps = 50
ZERO_CONST = '14.134725141734693790457251983562470270784257115699'

# %% Manual zeta function
def compute_zeta_manually(s, lim=100):
    zeta_val = mpmath.mpc(0)
    for i in range(1, lim + 1):
        n = mpmath.mpc(i)
        zeta_val += mpmath.power(n, -s)
    return zeta_val

# %% Outpus
print(f'Manual       : {compute_zeta_manually(mpmath.mpc(0.5, ZERO_CONST))}')
print(f'Mpmath lib   : {mpmath.zeta(mpmath.mpc(0.5, ZERO_CONST))}')

```

**Comment by skirpichev** [comment]
> I manually implemented the function

I doubt it's true.

> it does not converge for the "first" zero of zeta.  Why?

Why do you think that your sum converges at all for Re(s) < 1?  It's a correct definition for zeta(s) only for Re(s) > 1.

> Is the computation precision wrong?

It's just mathematically meaningless.

Though, in most cases you, probably, will want also to [temporary increase precision](https://mpmath.readthedocs.io/en/latest/basics.html#temporarily-changing-the-precision), computing a series.
