### ISSUE TITLE
mp.asin returns incorrect results at complex infinities

### ISSUE THREAD

**Issue by pearu** [mpmath/mpmath#793]
As in the title.

Reproducer (using 1.4.0a1.dev43+g0d287bf):
```python
>>> z = complex(mpmath.inf, mpmath.inf); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='nan', imag='+inf'), (0.7853981633974483+infj))
>>> z = complex(mpmath.inf, -mpmath.inf); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='nan', imag='-inf'), (0.7853981633974483-infj))
>>> z = complex(-mpmath.inf, mpmath.inf); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='nan', imag='+inf'), (-0.7853981633974483+infj))
>>> z = complex(-mpmath.inf, -mpmath.inf); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='nan', imag='-inf'), (-0.7853981633974483-infj))
>>> z = complex(mpmath.inf, 1); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='nan', imag='+inf'), (1.5707963267948966+infj))
>>> z = complex(mpmath.inf, 0); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='1.5707963267948966', imag='-inf'), (1.5707963267948966+infj))
>>> z = complex(mpmath.inf, -1); mpmath.mp.asin(z), mpmath.fp.asin(z)  # mp.asin vs expected
(mpc(real='nan', imag='-inf'), (1.5707963267948966-infj))
```

**Comment by skirpichev** [comment]
https://github.com/mpmath/mpmath/pull/795

**Comment by skirpichev** [comment]
Lets put this on hold per discussion in #795.  This may affect also other merged prs, that "fix" inconsistencies for mp vs fp contexts for complex numbers with infinite components.  E.g. https://github.com/mpmath/mpmath/issues/749

**Comment by pearu** [comment]
I am not sure that mpmath is going in the right direction considering the discussions here.

According to mpmath docs and its history, mpmath is "A Python library for arbitrary-precision floating-point arithmetic" and the mpmath.mp context is the face of mpmath. mpmath.fp is just a fast version of mpmath.mp with the restriction to 53-bit precision. In this respect, mpmath.mp and mpmath.fp must be consistent.

A specific problem I see here is that an attempt is made to handle complex infinities in a mathematically "correct" way that even major CAS's struggle with. While it is true that mpmath does much more than providing arbitrary-precision floating-point arithmetic such as numerical integration/differentiation, root-finding, special functions etc, it is still all about floating-point numeric that has well established grounds in terms of IEEE 754 and its successor standards. Resolving the complex infinities problem within mpmath is just not a mpmath business. To put it differently, mpmath.inf *is* a floating-point object while CAS's define special symbols that represent mathematical infinities that are useful for solving math problems. Needless to say, mpc is an extension of mpf from real to complex space but mpc still remains a floating-point concept that infinity instances does not need to capture all the properties of, say, Mathematica `DirectedInfinity` or `ComplexInfinity`. It would be fine to introduce, say, directed infinity to mpmath and make it compatible with `DirectedInfinity`, but by introducing a new structure that uses `mpc` (to represent direction and/or origin) which would be a complement tool to mpc infinities and not a replacement.

**Comment by skirpichev** [comment]
> I am not sure that mpmath is going in the right direction considering the discussions here.

As the proposed change introduced incompatibilities, I think we should give a chance to discuss that in related communities.  No need to rush.

Lets wait, say, a week, for a feedback.

> mpmath.fp is just a fast version of mpmath.mp with the restriction to 53-bit precision.

Maybe that was an intention, but de-facto - contexts are different in details.  The fp context has not just fixed precision (usually, 53-bit's), but it also has a signed zero.  The mp context has no signed zero (see #167 and #768).

> it is still all about floating-point numeric that has well established grounds in terms of IEEE 754 and its successor standards.

But the mp context is not IEEE 754-compatible in many details (not just ``-0.0``).  So, I don't think we should reject a proposal to be more SymPy-compatible on this ground.

**Comment by skirpichev** [comment]
> As the proposed change introduced incompatibilities

Hmm, in fact I was wrong here.  This convention was present in the mpmath v1.3.0 for ``asin(±oo)`` and ``acos(±oo)`` (for other arguments with infinite components there was nonsense).

But anyway, lets give people time to argue for changing this.

**Comment by pearu** [comment]
> > I am not sure that mpmath is going in the right direction considering the discussions here.
> 
> As the proposed change introduced incompatibilities, I think we should give a chance to discuss that in related communities. No need to rush.
>
> Lets wait, say, a week, for a feedback.

Fair enough.

> > mpmath.fp is just a fast version of mpmath.mp with the restriction to 53-bit precision.
> 
> Maybe that was an intention, but de-facto - contexts are different in details. The fp context has not just fixed precision (usually, 53-bit's), but it also has a signed zero. The mp context has no signed zero (see #167 and #768).

According to Kahan, IEEE 754 signed zeros resolves problems that involves computations with complex math functions, see [p.10](https://people.eecs.berkeley.edu/~wkahan/Math185/Derivative.pdf). I would consider the difference between mp and fp details as a defect in the mp part that can be fixed via introducing the signed zero to it.

> > it is still all about floating-point numeric that has well established grounds in terms of IEEE 754 and its successor standards.
> 
> But the mp context is not IEEE 754-compatible in many details (not just `-0.0`). So, I don't think we should reject a proposal to be more SymPy-compatible on this ground.

According to https://github.com/mpmath/mpmath?tab=readme-ov-file#4-known-problems, the lack of signed zero in mp context is a major issue, not a feature.

Also, I think SymPy is not the best reference for mpmath as it does not define floating-point arithmetic nor can it be a source of truth: there are just too many examples where its rewriting/simplification rules and (a lack of proper) assumption system may produce incorrect results. This is not specific to Sympy, of course, the usage of any CAS and the interpretation its results depends on the problem in hand which may define certain assumptions that a CAS cannot always represent because it was not defined for it or it would be simply impractical.

**Comment by skirpichev** [comment]
> a defect in the mp part that can be fixed via introducing the signed zero to it.

Or a new context, with more mpfr-like mpf type.

Certainly, not all context could have this notion.  How about iv?  Or arb/acb-like implementations for mpf/mpc?

As it was noted in the referenced issue, maybe we should introduce a new context, where mpf/mpc will behave much close to the IEEE 754.  And leave mp context as is.

> the lack of signed zero in mp context is a major issue, not a feature.

What about subnormals?

> Also, I think SymPy is not the best reference for mpmath

Sure, but this is a CAS library, built upon the mpmath.  We should realize, that certain changes might introduce problems for this library (or for the Diofant ;-)), ensure that there is a migration path in which library code could be adapted, etc.

For example, suppose we introduce signed zero for the mp context.  How SymPy people should change evalf() helpers to keep old continuity conditions on branch cuts (e.g. ``asin(2) == asin(2 - 0i) != asin(2 + 0i)``)?

**Comment by pearu** [comment]
> Certainly, not all context could have this notion. How about iv? Or arb/acb-like implementations for mpf/mpc?
> ...
> What about subnormals?

The answers to these depend on the demand: don't bother until a real need arises unless one just wants to have fun with implementing these features :) .

> As it was noted in the referenced issue, maybe we should introduce a new context, where mpf/mpc will behave much close to the IEEE 754. And leave mp context as is.

I think this is an excellent idea. Call it, say, `mp754`?

> For example, suppose we introduce signed zero for the mp context. How SymPy people should change evalf() helpers to keep old continuity conditions on branch cuts (e.g. `asin(2) == asin(2 - 0i) != asin(2 + 0i)`)?

Introducing a new IEEE 754-complaint mp context would resolve this issue.
