### ISSUE TITLE
SageMathCell's mpmath returns different answer ?

### ISSUE THREAD

**Issue by clairvoyante** [mpmath/mpmath#809]
```
from mpmath import mp, mpf, log
mp.prec=128
print(float(log(mpf('5.3e-7'))))
```
CPython3.12.4 + mpmath1.3.0 - ```-14.450388830400243```
SageMathCell - ```-14.450388830400245``` :
https://sagecell.sagemath.org/?z=eJxLK8rPVcgtyE0syVDIzC3ILyoB8nSAOE1HISc_nZcrt0CvoCg12dbQyIKXq6AoM69EIy0nP7FEAyirAVSmoW6qZ5yqa66uCQQAGZQYpQ==&lang=python&interacts=eJyLjgUAARUAuQ==

**Comment by oscarbenjamin** [comment]
This code has already been changed in mpmath master but my guess is that you're seeing the effect of this:
https://github.com/mpmath/mpmath/blob/b5c04506ef0cd4a1f1213f8389ee21c9c3551582/mpmath/libmp/libmpf.py#L277-L278

**Comment by skirpichev** [comment]
JFR, I've same answer in the master:
```pycon
>>> from mpmath import mp, mpf, log
>>> mp.prec=128
>>> print(float(log(mpf('5.3e-7'))))
-14.450388830400243
```

> my guess is that you're seeing the effect of this

@oscarbenjamin, oh, no - it's much simpler.  The sage has outdated cythonized replacements ("faster versions") for some libmp functions and for the mp context and mpf/mpc.  For instance, ``__float__`` dunder for the mpf type looks:
```cython
    def __float__(self):
        return libmp.to_float(self._mpf_)
```
while in the mpmath:
https://github.com/mpmath/mpmath/blob/ee1a8102665a2fba0faba6c2c0f0a064de92b522/mpmath/ctx_mp_python.py#L144
it takes into account the context's rounding mode. The ``to_float()`` has ``d`` (round down) as default, while context's default is ``n`` (round to nearest).  Here is a correct example both in Sage and in the mpmath:
```pycon
>>> from mpmath import mp, mpf, log, libmp
>>> mp.prec=128
>>> print(libmp.to_float(mp.log(mpf('5.3e-7'))._mpf_, 'n'))
-14.450388830400243
```

Fix is simple, but...  It seems, there are couple of problems with this approach.  (1) "faster versions" are outdated c.f. the mpmath master; (2) using gmpy2.mpfr type as a drop-in replacement for the mpf is incorrect: these types actually are different (mpfr has signed zero, mpf has no limits for exponents range).  Using pure-python code from the mpmath seems to be a better solution in perspective.

@clairvoyante, could you please open an issue wrt the sage repo?

**Comment by skirpichev** [comment]
> open an issue wrt the sage repo?

Done, see: https://github.com/sagemath/sage/issues/38223
