### ISSUE TITLE
eig in ascending order output

### ISSUE THREAD

**Issue by Rheoscope** [mpmath/mpmath#810]
In `DSYEV` of LAPACK, https://netlib.org/lapack/explore-html-3.4.2/d2/d8a/group__double_s_yeigen.html#ga442c43fca5493590f8f26cf42fed4044
there is some control of output eigenvalues in ascending order

```
  W is DOUBLE PRECISION array, dimension (N)
          If INFO = 0, the eigenvalues in ascending order.
```
Would it be possible to let `eig` in `mpmath` also sort eigenvalues and eigenvectors in ascending order?

**Comment by skirpichev** [comment]
There is ``eig_sort()`` method, which by default ("real") sort by increasing real part.  An example (from docs):
```pycon
>>> from mpmath import mp
>>> A = mp.matrix([[3, -1, 2], [2, 5, -5], [-2, -3, 7]])
>>> E, EL, ER = mp.eig(A, left=True, right=True)
>>> E, EL, ER = mp.eig_sort(E, EL, ER)  # f="real"
>>> mp.nprint(E)
[2.0, 4.0, 9.0]
>>> E, EL, ER = mp.eig_sort(E, EL, ER, f=lambda x: -mp.re(x))
>>> mp.nprint(E)
[9.0, 4.0, 2.0]
```

Feel free to reopen issue if you think it's not addressed properly.

**Comment by Rheoscope** [comment]
I have a question. Consider the following example,
```
from mpmath import mp
import numpy as np
mp.dps = 5

A = mp.matrix([[4, 2], [1, 3]])
E, EL, ER = mp.eig(A, left=True, right=True)


print('E',E)
print('ER', ER)
print('after sort')

E, ER = mp.eig_sort(E,  ER)  
print('E',E)
print('ER', ER)

```
I got
```
E [mpf('5.0'), mpf('1.9999981')]
ER [0.89443  -0.74536]
[0.44721   0.74536]
after sort
E [mpf('1.9999981'), mpf('5.0')]
ER [0.44721   0.74536]
[0.89443  -0.74536]
```
why exchanging the rows not columns, for the sorted eigenvectors? I think the eigenvectors are printed out as each column each one, i.e., (2,1) for eigenvalue 5 and (1,-1) for eigenvalue 2

**Comment by skirpichev** [comment]
> why exchanging the rows not columns, for the sorted eigenvectors?

Because you specified ER - as *left* eigenvectors for ``eig_sort()``.  See it's definition:
```python
def eig_sort(ctx, E, EL = False, ER = False, f = "real"):
```

Correct code in your example:
```pycon
>>> from mpmath import *
>>> mp.dps = 5
>>> A = mp.matrix([[4, 2], [1, 3]])
>>> E, EL, ER = mp.eig(A, left=True, right=True)
>>> E
[mpf('5.0'), mpf('1.9999981')]
>>> EL
matrix(
[['0.74536', '0.74536'],
 ['-0.44721', '0.89443']])
>>> ER
matrix(
[['0.89443', '-0.74536'],
 ['0.44721', '0.74536']])
>>> E, ER = mp.eig_sort(E, ER=ER)
>>> E
[mpf('1.9999981'), mpf('5.0')]
>>> ER
matrix(
[['-0.74536', '0.89443'],
 ['0.74536', '0.44721']])
```

**Comment by Rheoscope** [comment]
Thank you so much! By the way, how would I know that I don't need to provide value for `ctx` when using `eig_sort`?

**Comment by skirpichev** [comment]
> how would I know that I don't need to provide value for ctx when using eig_sort??

You did this.  ``eig_sort()`` attached as method to context object.  When you call ``mp.eig_sort()`` - the mp object will be first argument (usually named self) of this method.
