### ISSUE TITLE
Issues with iv.mpf/iv.mpc/mpi a, b, and mid attribute: it should be a mpf/mpc instance instead of another iv.mpf/iv.mpc.

### ISSUE THREAD

**Issue by haydenwong7bm** [mpmath/mpmath#814]
```python
>>> mp.prec = 16; mp.pretty = True
>>> iv_ = iv.mpf('0.3')
>>> iv_
[0.29999998212, 0.30000001192]
```
Expected:
```python
>>> iv_.a, iv_.b
(0.29999998212, 0.30000001192)
>>> type(iv_.a), type(iv_.b)
(<class 'mpmath.ctx_mp_python.mpf'>, <class 'mpmath.ctx_mp_python.mpf'>)
>>> mpi(0, 2).mid
1.0
```

Actual:
```python
>>> iv_.a, iv_.b
([0.29999998212, 0.29999998212], [0.30000001192, 0.30000001192])
>>> iv_.mid
[0.30000001192, 0.30000001192]
>>> type(iv_.a), type(iv_.b)
(<class 'mpmath.ctx_iv.ivmpf'>, <class 'mpmath.ctx_iv.ivmpf'>)
>>> mpi(0, 2).mid
[1.0, 1.0]
```

**Comment by skirpichev** [comment]
I don't think it's a bug, but I'll keep this open for a while to see if there are other opinions.

Current behaviour simplifies implementation.  Consider, for example, the ``__contains__()`` dunder method:
https://github.com/mpmath/mpmath/blob/8a4ce81f7f414f7a89e405cbafbd665f1a6e0099/mpmath/ctx_iv.py#L107-L109
If iv.mpf will be not closed and properties like ``a`` or ``mid`` will return something out of the iv context - function will be more complex.

**Comment by haydenwong7bm** [comment]
Reasons for supporting returning `mpf`/`mpc` objects:
When constructing an `iv` object, it is built by two `mpf`/`mpc` objects (`iv.mpf(mpf, mpf)`), so it makes sense to return `mpf`/`mpc` objects, in analogy to the `real` and `imag` attribute of `mpc(mpf, mpf)`, that will returns a `mpf` object.
I support adding `_a`, `_b`, `_mid` attributes (either 1 or 2 `_`s) to maintain the old behavior, while changing `a`, `b`, `mid` attributes to the aforementioned behavior. This convinces users to get the start and end points with the type `mpf`/`mpc`.

**Comment by skirpichev** [comment]
I'm not convinced that this worth compatibility break and code complications.  Current behaviour in fact mimic real/imag one for the mp context: this context has mpc and mpf "types", just as the iv context.  Note also, that the iv.mpf constructor support iv.mpf as endpoints:
```
>>> iv.mpf([iv.mpf([1, 2]), iv.mpf([2, 3])])
mpi('1.0', '3.0')
```

Feel free to propose a patch, however.

**Comment by haydenwong7bm** [comment]
I want to supplement that `mpf(mpi(a, b).x)` for `a`, `b` and `mid` does work properly:
```python
>>> mp.prec = 16; mp.pretty = True
>>> iv_ = iv.mpf('0.3')
>>> iv_
[0.29999998212, 0.30000001192]
>>> mpf(iv_.a), mpf(iv_.b)
(0.29999998212, 0.30000001192)
>>> mpf(iv.mpf(0, 2).mid)
1.0
```

`iv.mpc` does need further workaround:
```python
>>> iv_ = iv.mpc(mpi(0, 0), mpi(2, 2))
>>> mpc(mpf(iv_.real.mid), mpf(iv_.imag.mid))
(1.0 + 1.0j)
```

**Comment by skirpichev** [comment]
> iv.mpc does need further workaround

That's because mp.mpf.mpf_convert_arg() has a special case to create mpf from zero-width interval.  The mp.mpc has no similar code, maybe it should be.
