### ISSUE TITLE
Issues with the docs.

### ISSUE THREAD

**Issue by haydenwong7bm** [mpmath/mpmath#817]
In the Utility functions section:

> `fsub()`:
Exact <ins>addition</ins> can be inefficient and may be impossible to perform with large magnitude differences:

It should be:
> Exact <ins>subtraction</ins> can be inefficient and may be impossible to perform with large magnitude differences:

----

> `mag()`:
Quick logarithmic magnitude estimate of a number…

But the implementation should return the exponent exactly (if I am correct), maybe change to:
> Returns an integer or infinity _m_ such that 2<sup>_m_-1</sup> ≤ |x| < 2<sup>_m_</sup>.

**Comment by skirpichev** [comment]
> Exact subtraction can be inefficient and may be impossible to perform with large magnitude differences:

Indeed.

> But the implementation should return the exponent exactly

No, why do you think so?!  It's upper bound, not optimal.

**Comment by haydenwong7bm** [comment]
> > Exact subtraction can be inefficient and may be impossible to perform with large magnitude differences:
> 
> Indeed.
> 
> > But the implementation should return the exponent exactly
> 
> No, why do you think so?! It's upper bound, not optimal.

Sorry, I just looked at the `libmpf.py` and `ctx_mp_python.py` code by intuition. I don't exactly know how it works.

In additionally, I found another issue with the docs:
In the Matrix section:

> Linear equations:
If you don’t trust the result, use residual to calculate the residual ||A*x-b||:

The ||A*x-b|| should be rendered in math instead of plain text.
