### ISSUE TITLE
nstr(mpf('inf')) prints '+inf' (should be 'inf')

### ISSUE THREAD

**Issue by skirpichev** [mpmath/mpmath#827]
While for finite numbers positive sign - ignored.  This also inconsistent across contexts:
```pycon
>>> nstr(mp.mpf('inf'))
'+inf'
>>> nstr(fp.mpf('inf'))
'inf'
```

**Comment by skirpichev** [comment]
@oscarbenjamin, this breaks LatexPrinter._print_Float() in SymPy.  Though, it seems this case wasn't tested.

**Comment by oscarbenjamin** [comment]
Okay, thanks for the heads up.

**Comment by oscarbenjamin** [comment]
Wait what exactly is it that breaks?
```python
In [8]: latex(Float('inf'))
Out[8]: '\\infty'
```

**Comment by skirpichev** [comment]
Oh, I see, sorry for a false alarm.  It seems, there is no Float('inf') in SymPy anymore, it's just ``oo`` singleton.

Now this code is dead:
https://github.com/sympy/sympy/blob/9c426bcd1fd653bb43304dfe973f47f871d0011c/sympy/printing/latex.py#L482-L485

**Comment by oscarbenjamin** [comment]
> there is no Float('inf') in SymPy anymore, it's just `oo` singleton

I'm still not sure how I feel about that decision.

**Comment by skirpichev** [comment]
Yeah, that's something uneasy to follow.  I would rather appreciate removing of the NegativeInfinity.
