### ISSUE TITLE
[doc] recommend gmpy2 instead of gmpy

### ISSUE THREAD

**Issue by jwuttke** [mpmath/mpmath#840]
https://mpmath.org/doc/current/setup.html#using-gmpy-optional recommends using `gmpy` but does not say how to install that package. It would be helpful to indicate that up-to-date pip package is called `gmpy2` (https://pypi.org/project/gmpy2/), whereas "pip install gmpy" fails with complaints about missing `longintrepr.h` or other, obscure compiler errors.

**Comment by skirpichev** [comment]
Beware that docs for development version on mpmath.org are outdated, see #709.  Readme file now points to https://mpmath.readthedocs.io/.

> does not say how to install that package

It does, see https://mpmath.readthedocs.io/en/latest/setup.html#using-pip

> It would be helpful to indicate that up-to-date pip package is called gmpy2

Yeah, probably you are right.  I'll make a patch.

**Comment by skirpichev** [comment]
See #839
