### ISSUE TITLE
hang in findroot

### ISSUE THREAD

**Issue by zhangzhen** [mpmath/mpmath#869]
running the following code snippet will hang at the line of nsolve in the function _calc_abcd_with_sp.

```
from sympy import symbols, nsolve, sqrt

def _calc_abcd_with_sp(phi, abcd0):
    a0, b0, c0, d0 = abcd0
    N0 = sum(abcd0)
    S0 = b0 / d0
    T0 = c0 / d0

    a, b, c, d = symbols("a b c d", Positive=True, Real=True)

    eq1 = N0 - (a + b + c + d)
    eq2 = b - S0 * d
    eq3 = c - T0 * d
    eq4 = phi - (a * d - b * c) / sqrt((a + b) * (c + d) * (a + c) * (b + d))

    print(phi, abcd0, flush=True)
    try:
        solutions = nsolve(
            (eq1, eq2, eq3, eq4), (a, b, c, d), (a0, b0, c0, d0), maxsteps=2, tol=1e-6, verbose=True
        )
    except (
        ValueError,
        ZeroDivisionError,
    ):
        return ()
    # print(phi, abcd0, flush=True)

    a_, b_, c_, d_ = map(float, [sol[0] for sol in solutions.tolist()])

    if a_ < 0 or b_ < 0 or c_ < 0 or d_ < 0:
        return ()
    abcd = round_numbers((a_, b_, c_, d_))
    if not is_valid_abcd(abcd):
        return ()
    return abcd


def round_numbers(numbers):
    rounded = np.floor(numbers).astype(int)

    original_sum = sum(numbers)
    rounded_sum = sum(rounded)
    difference = round(original_sum - rounded_sum)

    for i in np.argsort([n - r for n, r in zip(numbers, rounded)])[::-1][:difference]:
        rounded[i] += 1
    return tuple(rounded.tolist())


def is_valid_abcd(abcd):
    a, b, c, d = abcd
    return a >= 0 and b >= 0 and c >= 0 and d > 0 and a + b > 0 and a + c > 0

phi = -0.44
abcd0 = (38, 34, 0, 49)
_calc_abcd_with_sp(phi, abcd0)
```

**Comment by skirpichev** [comment]
@zhangzhen, I realize that nsolve() internally uses mpmath's findroot in some way.  But it's SymPy's function, so please next time either report such issues to the SymPy project first, or try to provide a minimal example, using mpmath's functions.

It seems your starting point wasn't good and mpmath's code in MDNewton() stuck with checking strict equality.  I think solver should just quit if either function or jacobian produce complex values.

Could you please verify that changing this line:
https://github.com/mpmath/mpmath/blob/14fe1b6049e8da903ded3beef7a5fa0aec9baf9c/mpmath/calculus/optimization.py#L666
to ```if self.ctx.chop(x1) == self.ctx.chop(x0):``` fix issue for you?

**Comment by zhangzhen** [comment]
> to `if self.ctx.chop(x1) == self.ctx.chop(x0):` fix issue for you?

bad initial guess will lead to fall into the infinite while loop at line 665 since no smaller newnorm is found. see the two lines underlined with the red color in the following code screenshot.
<img width="770" alt="image" src="https://github.com/user-attachments/assets/0b686942-e196-478c-a80f-760059725ec5">

**Comment by skirpichev** [comment]
Can you, please, answer to my question?

**Comment by zhangzhen** [comment]
> Can you, please, answer to my question?

mpmath has been installed via pip install sympy. how can i verify the change you suggested is correct? Should i git clone this repo, and then change the code and pip install -e ./ ?

**Comment by skirpichev** [comment]
You can path to installed mpmath's ``__init__.py`` like this:
```
>>> import mpmath
>>> mpmath.__file__
'/home/sk/venv/dev3.11/lib/python3.11/site-packages/mpmath/__init__.py'
```

**Comment by zhangzhen** [comment]
> Could you please verify that changing this line:
> 
> https://github.com/mpmath/mpmath/blob/14fe1b6049e8da903ded3beef7a5fa0aec9baf9c/mpmath/calculus/optimization.py#L666
> 
> 
> to `if self.ctx.chop(x1) == self.ctx.chop(x0):` fix issue for you?

yes. i verified that this change fixed my issue.

**Comment by skirpichev** [comment]
More simple reproducer:
```py
from mpmath import findroot, sqrt
f = [lambda x: sqrt(x) + 1]
findroot(f, [-1], multidimentional=True)
```
