### ISSUE TITLE
no floor division, mod and divmod for mpc types

### ISSUE THREAD

**Issue by haydenwong7bm** [mpmath/mpmath#882]
The floor function is defined for `mpc` types, so floor division should also be defined for `mpc` type: `z1 // z2 = floor(z1 / z2)`. So, the mod function should also be defined for `mpc` types: `z1 % z2 = z1 - z2 * (z1 // z2)`. However, the floor function, floor division, mod and divmod is not defined for built-in `complex` type.

**Comment by skirpichev** [comment]
> The floor function is defined for mpc types

You meant for the mpf type?  It has floor division, because it implements the numbers.Real.

>  so floor division should also be defined for mpc type: z1 // z2 = floor(z1 / z2)

That doesn't make sense.  What's the floor of a complex number?

**Comment by haydenwong7bm** [comment]
> You meant for the mpf type? It has floor division, because it implements the numbers.Real.

I am really discussing about the mpc type.

> That doesn't make sense. What's the floor of a complex number?

floor() is defined for complex number: floor(_z_) = floor(Re(_z_)) + _i_\*floor(Im(_z_)). So _z1_ // _z2_ = floor(_z1_ / _z2_) = floor(Re(_z1_ / _z2_)) + _i_\*floor(Im(_z1_ / _z2_)).

**Comment by skirpichev** [comment]
> floor() is defined for complex number

```pycon
>>> math.floor(mpc(1j))
Traceback (most recent call last):
  File "<python-input-8>", line 1, in <module>
    math.floor(mpc(1j))
    ~~~~~~~~~~^^^^^^^^^
TypeError: must be real number, not mpc
>>> math.floor(1j)
Traceback (most recent call last):
  File "<python-input-9>", line 1, in <module>
    math.floor(1j)
    ~~~~~~~~~~^^^^
TypeError: must be real number, not complex
```

**Comment by haydenwong7bm** [comment]
I mean the mpmath's `floor()` is defined for `mpc` types.
Also, here is an example for mod of complex number (especially for Gaussian integers):
Mod(3e+4πi, e+πi) = (3e+4πi) - (e+πi) floor((3e+4πi) / (e+πi)) =  (3e+4πi) - (e+πi) floor(3.57… + 0.49…i) = (3e+4πi) - (e+πi)·3 = πi
(Also check out Wolfram Language: https://wolfram.com/xid/02cbm-ctu0mc, https://www.wolframalpha.com/input?i=%283e%2B4%CF%80i%29+%2F+%28e%2B%CF%80i%29)
