### ISSUE TITLE
[Docs] Root-finding requires solver-name-guessing

### ISSUE THREAD

**Issue by jwuttke** [mpmath/mpmath#884]
How to guess from page https://mpmath.org/doc/current/calculus/optimization.html that the keyword argument for the bisection solver is not any of
- solver=Bisection
- solver='bisection'
- solver='Bisection'

but
- solver='bisect'

???

**Comment by skirpichev** [comment]
```
solver

    a generator for f and x0 returning approximative solution and error
[...]
solver has to be callable with (f, x0, **kwargs) and return an generator yielding
 pairs of approximative solution and estimated error (which is expected to be
positive). You can use the following string aliases: ‘secant’, ‘mnewton’,
‘halley’, ‘muller’, ‘illinois’, ‘pegasus’, ‘anderson’, ‘ridder’, ‘anewton’, ‘bisect’
```

I would appreciate improving docs, especially with concrete proposals.  But this issue seems invalid: there is no need to guess.
