### ISSUE TITLE
Add support for Gompertz constant

### ISSUE THREAD

**Issue by RotemKalisch** [mpmath/mpmath#887]
I'm using `mpmath` for my research for a while now and I have noticed that there is currently no implementation for the [Gompertz constant ](https://en.wikipedia.org/wiki/Gompertz_constant).
The implementation should be fairly simple, as it's mathematically defined as `-mp.e * mp.ei(-1)`.

**Comment by skirpichev** [comment]
> no implementation for the [Gompertz constant](https://en.wikipedia.org/wiki/Gompertz_constant).

As well as for many other mathematical constants, e.g. the Feigenbaum constant.

> The implementation should be fairly simple, as it's mathematically defined as -mp.e * mp.ei(-1).

To me it's an argument to *not* include this constant.  The mp.constant() interface is public (though maybe not well documented or discoverable).  So, you can define constants by yourself.

**Comment by RotemKalisch** [comment]
I understand the desire to keep the codebase clean and simple, but other than that why wouldn't you want the library to support as many mathematical constants as possible?
The fact that this feature is relatively simple (borderline syntactic sugar) does not mean that it's a less of a feature. The reason I have decided to ask for it is that I believe many researchers that are less comfortable coding might not realize this is a possibility (definitely if it's under-documented), or even see this as a barrier.

In the case that this feature request is rejected, I would like to ask for documentation regarding the usage of `mp.constant()`. I have only found [this](https://mpmath.org/doc/current/functions/constants.html) page which does not showcase how to define new constants.

**Comment by skirpichev** [comment]
> wouldn't you want the library to support as many mathematical constants as possible?

Should we put here 2*pi (e.g. as Python's math/cmath modules) or 4*pi?  There is a lot of constants, even named.

Probably, this does make sense if some constant is used by downstream's (e.g. SymPy), non-trivial to compute, etc.

Lets keep this for a while, maybe there are other opinions.

> I would like to ask for documentation regarding the usage of mp.constant()

That definitely does make sense for me.  But probably this will wait for https://github.com/mpmath/mpmath/issues/683.

**Comment by skirpichev** [comment]
Ok, I'm closing it in favor of https://github.com/mpmath/mpmath/issues/683.
