### ISSUE TITLE
multithreaded runtests.py

### ISSUE THREAD

**Issue by vks** [mpmath/mpmath#99]
bc.. It should be trivial to run several tests at once using Parallel Python or
something else. py.test offers such a feature already, so maybe we should
use it instead of a own solution.

p. Original issue for "#99":https://github.com/fredrik-johansson/mpmath/issues/99: "http://code.google.com/p/mpmath/issues/detail?id=59":http://code.google.com/p/mpmath/issues/detail?id=59

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

p. Original owner: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by warnerjon12** [comment]
> py.test offers such a feature already
I would like to know what you meant by this. I couldn't find anything and I was having issues using the multiprocessing library. Specifically it complained that some stuff was not picklable, and I cannot fix that without making substantial organizational changes or using other third-party libraries (and it is better not to rely on as many third-party libraries).

**Comment by vks** [comment]
@warnerjon12 I haven't used pytest for many years, but IIRC there was a command line option to run the tests using multiple processes.

I'm not sure what you are trying to do while getting those errors, but everything sent between processes using `multiprocessing` has to be pickled.

**Comment by skirpichev** [comment]
I think we could use pytest-xdist plugin.  We run CI tests with pytest anyway...
